### ISSUE TITLE
Add dynamic query parameters for checks

### ISSUE THREAD

**Issue by heipei** [checkly/public-roadmap#100]
I would love to have an option to have a random / changing string or query parameter in the API checks. That way I could for example append the current timestamp as a query parameter to the request for the purpose of bypassing cached pages.

**Comment by tnolet** [comment]
@heipei that is actually already a thing! Guess we could highlight that more. Just enter `{{` and you will get a range of options like UUID, moment etc. Relevant docs are here: https://www.checklyhq.com/docs/api-checks/variables/#using-handlebars-helpers--built-in-variables

![image](https://user-images.githubusercontent.com/3802923/108060689-845bb380-7057-11eb-8641-b7e7016d58f4.png)

**Comment by heipei** [comment]
Thanks, that's perfect!
