### ISSUE TITLE
API Checks: Secondary requests based on response

### ISSUE THREAD

**Issue by heipei** [checkly/public-roadmap#101]
Not sure if this is the best way to implement this feature, but for some API checks it would be really useful if we could parse the output from the API check and then do a secondary request with data from the output, and that check would be what's actually measured.

Use-case is a Search API that returns the latest hits, and the for one of the hits I might want to issue a request to retrieve the result.

**Comment by tnolet** [comment]
Hi @heipei I think you are looking for multi step API checks. We have an earlier request for this. See https://github.com/checkly/public-roadmap/issues/46

For now, I advise to just use setup & teardown scripts. Many users do exactly what you mention in a setup script. Fetch some data and instrument the "real" API check with that data. Have a look here https://www.checklyhq.com/docs/api-checks/setup-teardown-scripts/#setup-script-examples

**Comment by tnolet** [comment]
I'm closing this in favor of the #46 so please give that one a 👍
