### ISSUE TITLE
Public Status Dashboards: Responsive & More Info

### ISSUE THREAD

**Issue by heipei** [checkly/public-roadmap#102]
Hello Team,

I would really like for the public dashboard pages to be more useful than they are today. To that end, I think the following features would be helpful to me:

- Page should be responsive as it's often checked on-the-go via phone.
- Page should show should show useful information (e.g. dropdown on click), such as:
  - Type, Date and Locations of last incidents (e.g. timeout vs. format error)
  - Number of check criteria for each check
- Some information could be condensed: Check interval and last-checked date could be smaller, under service name

Right now if I check the status page it doesn't help me at all, except being able to tell that there was a red bar at some point. If I want to be able to use it I need to at least be able to inspect each service, when it started failing, what the failure criteria were, and when it came back to working state.

**Comment by tnolet** [comment]
@heipei we have a tracking issue that — I think — lists a lot of your concerns already. See https://github.com/checkly/public-roadmap/issues/65

Ok, if I close this one in favor of the tracking issue? Let me know.

**Comment by heipei** [comment]
Yep, same as on my other issue, sounds perfect, closing this one.
