### ISSUE TITLE
Public Status Dashboards: Decrease weight of status page & remove intrusive tracking

### ISSUE THREAD

**Issue by heipei** [checkly/public-roadmap#103]
Hello Team,

In my opinion, the public dashboard page could be a lot more lightweight. It is currently pulling down 76 resources with 2.6MB to display a table and some bar graphs without any additional features (not even responsiveness). Some of the resources include cancerous things like Google Tag Manager, Intercom, Headway App, Plausible and Sentry. I don't ever want my users or myself be tracked when they are accessing a tiny Status dashboard, and none of these third party dependencies seem to offer any benefit or feature to the status dashboards anyway.

**Comment by tnolet** [comment]
@heipei already mentioned on the other issue. We have a tracking issue for this. See https://github.com/checkly/public-roadmap/issues/65

Let me know if we can close this one.

**Comment by heipei** [comment]
Thanks Tim, sounds perfect, now I feel silly for not checking existing issues. Closing this one.
