### ISSUE TITLE
expose the ENVIRONMENT_URL as a query parameter on the command line triggers

### ISSUE THREAD

**Issue by robbydooo** [checkly/public-roadmap#105]
**Describe the solution you'd like**

Based on discussions with support, it would be great to add support for passing the environment url as a query parameter on the command line triggers.

This would allow preview urls generated by services such as Vercel & Netlify to be tested as part of a github/gitlab ci/cd workflow.

Example:

```
curl -X GET "https://api.checklyhq.com/checks/<uuid>/trigger/xxx?deployment=true&repository=acme/customer-api&preview-url=https://some-preview-domain.com"
```

**Comment by tnolet** [comment]
@robbydooo thanks for contributing. We will pick this up.

**Comment by tnolet** [comment]
@robbydooo this is now live! Check the webapp or read our docs at https://www.checklyhq.com/docs/cicd/triggers/#example-2-using-the-environmenturl
