### ISSUE TITLE
Sub-second Response time limits

### ISSUE THREAD

**Issue by cpressland** [checkly/public-roadmap#107]
**Describe the solution you'd like**
The ability to set the response time slider in milliseconds rather than seconds. Example, we recently had an issue that didn't spike over 1s, but did over 700ms, this breaches an internal SLA which we may have had a faster response to if we could degrade our API checks sooner.

**Comment by tnolet** [comment]
@cpressland this sounds like a totally fair enhancement we should roll out! I'm thinking we can stage the 0s to 1s — possibly 2s — range with some  250ms intervals in the UI.

In the mean time, you could already patch this through our API, as the slider in the UI is just for convenience.
See https://www.checklyhq.com/docs/api#update-a-check and reference the `degradedResponseTime` and `maxResponseTime` properties.

**Comment by tnolet** [comment]
@cpressland we just added this to our current work load. Should not be too long.
