### ISSUE TITLE
Private Locations

### ISSUE THREAD

**Issue by cpressland** [checkly/public-roadmap#111]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability to host a checkly runner from within our network to determine internal availability and response times. This helps us determine if our API is being genuinely slow or we have network issues.

**Additional context**
Other synthetics providers offer this as a service, example [Datadog](https://docs.datadoghq.com/getting_started/synthetics/private_location/)

**Comment by tnolet** [comment]
@cpressland this is a huge topic on our internal radar for a period. 

All I can say is that we will have this at a certain stage. The reference to Datadog is valid and we will probably follow a similar pattern: some container you run inside your firewall that uses an outgoing connection to fetch work loads.

Config, reporting, alerting etc. will just use our UI and API.

I took the liberty to edit your issue title a bit so folks can find this and upvote.

**Comment by tnolet** [comment]
@cpressland I'm also adding the tracking label here. We have an internal tracking list too, but it would be good for other users/customers to vote here with a 👍

**Comment by julienroybkn** [comment]
Hi @tnolet do you have an idea of an approximate delivery ( even in quarter ) ?
It will be a game changer in our provider selection decision.
Thanks a lot.

**Comment by tnolet** [comment]
@julienroybkn we are ramping up for a tech preview. Let me connect you to @brampling who is the PM on this. He can give you all the details.

**Comment by julienroybkn** [comment]
@tnolet Great, thanks.

**Comment by brampling** [comment]
@julienroybkn We have a technical preview available now and will be production ready in Q2.
