### ISSUE TITLE
Ignore alerts when ssl is invalid or bypass certificates invalid 

### ISSUE THREAD

**Issue by claudiofp** [checkly/public-roadmap#118]
Within the API check service (API CHECK) is it possible to place a configuration to ignore HTTPS / SSL errors? Today we have an API that unfortunately the client is unable to verify his certificate. And the service is returning Error: unable to verify the first certificate.

It would be interesting to be able to add a configuration that would by-pass the certificate or something similar.

**Comment by tnolet** [comment]
@claudiofp sorry for the late reply, this slipped through. We get this question more often. Noted.

**Comment by Urinprobe** [comment]
I am having the same issue. This is basicly what is keeping me from using checkly, sadly.

As this is based on the `request` library I know that the option exists. Basicly passing the option `rejectUnauthorized: false` to the agent. The implementation should be fairly straight forward.

**Comment by tnolet** [comment]
@Urinprobe @claudiofp we have this in development right now

**Comment by tnolet** [comment]
https://github.com/checkly/checkly-webapp/pull/1994

**Comment by Antoine-C** [comment]
@Urinprobe @claudiofp we added an option "skip SSL" on API checks to bypass certificates validation, you can also find this parameter inside the "request" param when creating a check through [our API](https://www.checklyhq.com/docs/api#operation/postV1Checks). 

<img width="1183" alt="Capture d’écran 2022-02-07 à 09 21 35" src="https://user-images.githubusercontent.com/3541876/152750750-807e640f-52ed-4021-b7c9-7fe3f9626fc5.png">
