### ISSUE TITLE
Can the error message be improved in case API is timing out?

### ISSUE THREAD

**Issue by aliasgerkw** [checkly/public-roadmap#120]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
I tried hitting one API which is usually timing out, in response I am getting only "Your Check failed" but no error logs or message about the reason. 

**Describe the solution you'd like**
Even if there is a timeout it will be good to mention the time api si taking.

**Describe alternatives you've considered**
None as of now.

**Additional context**
<img width="1144" alt="Screenshot 2021-04-21 at 5 01 26 PM" src="https://user-images.githubusercontent.com/51911147/115547143-8d6d3900-a2c3-11eb-9a80-8972c1a2d772.png">

**Comment by tnolet** [comment]
@aliasgerkw that looks more like a UI bug to me! I'm pretty sure the message returning from our API has more details that we should surface on the screen. Would you mind sharing the URL privately through our support channel? I would be happy to dive in.

**Comment by aliasgerkw** [comment]
Sure @tnolet 
Sent the check URL in chat.

**Comment by tnolet** [comment]
@aliasgerkw this has been fixed, actually for a while already! Sorry to reply so late.

**Comment by aliasgerkw** [comment]
thanks @tnolet
