### ISSUE TITLE
Allow importing of the 'net' Node.js module

### ISSUE THREAD

**Issue by mxschmitt** [checkly/public-roadmap#123]
**Is your feature request related to a problem? Please describe.**

I'm maintaining a service which can only be checked if its online via making a TCP connection and asserting if the connection was accepted / transferred the expected data.

**Describe the solution you'd like**

Checkly has Browser Checks which execute arbitrary Node.js scripts. These can also perfectly be used to allow users to use the 'net' module to make a connection to a server if they want.

**Describe alternatives you've considered**

N/A

**Additional context**

An example would look like:

```js
const net = require('net');

(async () => {
  const socket = net.createConnection(10011, "123.123.123.123");

  await new Promise(resolve => socket.on('data', resolve))

  socket.end()
})()
```

Currently this results in `UserScript VMError [Error]: Access denied to require 'net'`

This is also my last blocker from fully moving over from uptimerobot to Checkly for my checks. Thanks for all the great work!

**Comment by tnolet** [comment]
@mxschmitt thanks for reporting this. I guess in the end you want to have TCMP and maybe ICMP checks? If so, please bump this one https://github.com/checkly/public-roadmap/issues/96

Adding the `net` module to the whitelist is something we can consider though.

**Comment by tnolet** [comment]
@mxschmitt I'm closing this one in favour of the mentioned tracking ticket!
