### ISSUE TITLE
Allow duplicating group from UI

### ISSUE THREAD

**Issue by maetolay** [checkly/public-roadmap#127]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**

Currently from a user perspective. We want to have groups of checks for every environment that we manage. Normally what the user would do

1. Create a group
2. Add checks
3. Duplicate the group and change URL and variables for other environments

However, currently, it is not possible to duplicate the group which is a tedious job.

**Describe the solution you'd like**

Beable to duplicate group from UI

**Comment by tnolet** [comment]
@maetolay great suggestion and sorry for the late reply.

**Comment by tnolet** [comment]
@orcunilbeyli We should add this to our UX audit!

**Comment by tnolet** [comment]
@orcunilbeyli Do we have this in the upcoming batch?

**Comment by orcunilbeyli** [comment]
@tnolet Didn't add this to current batch while epic was open but this is gonna be in the next round.

**Comment by tnolet** [comment]
@maxigimenez @jenya-II @Antoine-C this is seems like something we can add pretty soon. I agree it makes sense. Many endpoints follow similar patterns.

**Comment by brampling** [comment]
@maetolay This has now been implemented. https://headwayapp.co/checkly-changelog/duplication-enhancements-219031
