### ISSUE TITLE
Support to setup CI/CD triggers for checks within a group

### ISSUE THREAD

**Issue by tdeekens** [checkly/public-roadmap#129]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**

When defining checks inside of groups, the group controls the CI/CD triggers. As a result one can "only" configure a CI/CD trigger for a the whole group and not a subset of checks within the group. 

Depending on the usage and structure of groups, this can be suboptimal as unrelated checks are run by a CI/CD trigger.

**Describe the solution you'd like**

I can see two solutions addressing the issue:

## 1. Allow CI/CD triggers for checks within a group

If a group has a CI/CD trigger configured then no check can have a trigger.
If a group has no CD/CD trigger configured then each check can have a CI/CD trigger.

## 2. Allow multiple CI/CD triggers per group using tags as selectors

This alternative might be more powerful than option 1. As soon as check lives within a group, CI/CD triggers can only be configured on a group level. However, one can setup multiple checks and can specific tags to select checks to be triggerd.

**Group A**
- Check A: tag-b
- Check B: tag-a
- Check C: tag-b
- Check D: tag-c

**CI/CD Trigger for Group A**
1. Trigger A: tab-b
2. Trigger B: tab-a

In the example checks are selected by tags for the triggers. While Trigger A will invoke two checks (A and C), Trigger B will only invoke Check B while no trigger invokes Check D.

**Comment by tnolet** [comment]
@tdeekens I quite like option 2. This seems more elegant and reduces complexity with regard to managing resources at multiple levels.

**Comment by tdeekens** [comment]
Hi, @tnolet! I also like option 2 more. Option 1 also means that a user has to potentially trigger multiple triggers using the API which isn't ideal.

**Comment by tnolet** [comment]
@tdeekens this is now achievable using the `npx checkly trigger` command and using the `--tags` flags. https://www.checklyhq.com/docs/cli/command-line-reference#npx-checkly-trigger
