### ISSUE TITLE
Status badge (to add it to a git repo's README.md)

### ISSUE THREAD

**Issue by Zerotask** [checkly/public-roadmap#131]
**Is your feature request related to a problem? Please describe.**
I'd like to show some information about the uptime quality of a website in form of a status badge for git repositories (markdown).

**Describe the solution you'd like**
A regular markdown status badge which you can add to a README.md

**Comment by tnolet** [comment]
@Zerotask yes, this is very cool and we want to do it. Even more, we were discussing this already internally. The question I would have regarding this is at what level would you want the badge "report" status.

- account wide
- per check
- per check group

Would you also want to have some form of performance / response time information in there, or just a binary "up/down" status?

In other words, what would you expect such a badge to report?

**Comment by Zerotask** [comment]
> The question I would have regarding this is at what level would you want the badge "report" status.

I guess account wide doesn't make much sense. In most cases you want to show the uptime for a specific website or service (like an API) and since you can have multiple tests per website / service you mostly want to show stats about a check group, but it can also be useful to show stats about a single check.

> Would you also want to have some form of performance / response time information in there, or just a binary "up/down" status?

I'd like to have the option to choose between a percentage (98.96 % uptime) and / or the average response time. Either one of those 2 information or a badge with both information on it.

**Comment by alainsharemat** [comment]
Came here to create the same feature request :)

We are using healthchecks.io to monitor our cron jobs. They provides badges that can be embedded anywhere. It's just an url to an svg file, that has some magic to refresh itself without reloading the page that displays it.

They generate a global badge plus one for each tag. I love the fact that it's based on tag, you can do what you want and have badge that covers one, or many checks.

I'd prefer to have a badge that shows the active status of checks (red/yellow/green), more than percentages.

**Comment by tnolet** [comment]
Pasting reference for inspiration https://repobeats.axiom.co/

**Comment by mbernasocchi** [comment]
Based on groups and/or tags would be great. I do not see a real use for account-wide, single test could also be useful.

**Comment by brampling** [comment]
@Zerotask @alainsharemat @mbernasocchi This has been implemented. It needs to be enabled in Account Settings and you can see usage details here: https://developers.checklyhq.com/reference/getv1badgescheckscheckid

We will be adding some additional functionality to the UI to make this easier in a later release.
