### ISSUE TITLE
Can we have last edited by feature for each check?

### ISSUE THREAD

**Issue by aliasgerkw** [checkly/public-roadmap#135]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
Currently in a team there is no history maintained over the checks so that I can revert to a version if something goes wrong, also it does not provide who edited the check last.

**Describe the solution you'd like**
Something like git version we can see and restore a history version along with audit of who made the change and when

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by tnolet** [comment]
Hey @aliasgerkw we're working on enabling storing your checks in Git! It will be very cool! In the meantime, I hear you on the audit trail part. Please give this issue a bump https://github.com/checkly/public-roadmap/issues/87

If ok, I will close this issue.

**Comment by aliasgerkw** [comment]
Thanks Tim
