### ISSUE TITLE
Set default edit check run script location

### ISSUE THREAD

**Issue by bartdeslagmulder** [checkly/public-roadmap#136]
**Is your feature request related to a problem? Please describe.**
Not a problem but more an improvement...

When you edit (or create) a check you can try it by clicking "Run Script". By default the location used to run this script is set to "N. Virginia".
![checkly_edit_check](https://user-images.githubusercontent.com/62296/125679391-5bc98a77-99c9-4695-9dec-fa85a3ac904c.png)

**Describe the solution you'd like**
When I run my scripts I change the location to "Paris". But I need to do this each time I want to edit a check. It would be nice if we could set this default location in some settings somewhere... that way I don't need to change it all the time.
![image](https://user-images.githubusercontent.com/62296/125679884-135a8982-b384-4f04-bbd3-25f18d2ead6c.png)

**Describe alternatives you've considered**
Instead of adding another setting you could remember the selection via a cookie or localStorage entry.

Really like Checkly so far! 👏

**Comment by tnolet** [comment]
@bartdeslagmulder we actually have — or should I say "had" — that feature but I think we broke it. Sorry. Pinging @maxigimenez

**Comment by bartdeslagmulder** [comment]
Ok, thanks for having a look. 
You should write a test for it... ;-)

**Comment by tnolet** [comment]
@bartdeslagmulder shipping a fix for this today!

**Comment by maxigimenez** [comment]
@bartdeslagmulder fix has been released! :)

**Comment by bartdeslagmulder** [comment]
Working great! Thanks for the quick fix!
