### ISSUE TITLE
Duplicate check via group edit isn't working

### ISSUE THREAD

**Issue by bartdeslagmulder** [checkly/public-roadmap#137]
**Issue**
When you duplicate a check from the dashboard you land on a new page with a **copyCheckId** param:
https://app.checklyhq.com/checks/browser/create/?copyCheckId=xxx
![checkly_duplicate_from_dashboard_ok](https://user-images.githubusercontent.com/62296/126081827-8554feee-0018-4fd2-878d-52215bad4ce9.png)
![checkly_duplicate_from_dashboard_2_ok](https://user-images.githubusercontent.com/62296/126081829-4b1a6300-b0db-4155-a5a9-6bc374ee0c37.png)

When you try to duplicate a check from within a group edit (https://app.checklyhq.com/groups/xxx/edit) you'll get the basic check content when you click the "open in full editor" link because the **copyCheckId** param is missing:
_Duplicate check_
![checkly_duplicate_from_group_edit_nok](https://user-images.githubusercontent.com/62296/126081846-6c245493-0749-4b74-a758-5408be82ac0a.png)
_New check is created_
![checkly_duplicate_from_group_edit_1_nok](https://user-images.githubusercontent.com/62296/126081910-dd432c75-1898-4834-8289-e6aef04f9897.png)
_Click the "open in full editor" link_
![checkly_duplicate_from_group_edit_2_nok](https://user-images.githubusercontent.com/62296/126081913-f01e5ee7-28b7-4a8b-a37b-c21d6cdfafe6.png)

**Fix**
If you append "&copyCheckId=xxx" in the "open in full editor" link you'll get the copy you want.

**Comment by tnolet** [comment]
@maxigimenez @ndom91 can you have a look?

**Comment by ndom91** [comment]
Yeah so you have to hit "Save" explicitly after creating the check, before going to "open in full editor"

**Comment by bartdeslagmulder** [comment]
Cool, thanks! 👍

**Comment by maxigimenez** [comment]
@bartdeslagmulder thanks for reporting this issue! We just released a fix for it.

**Comment by bartdeslagmulder** [comment]
Thank you!
