### ISSUE TITLE
Add Faker to node module dependencies

### ISSUE THREAD

**Issue by grob3** [checkly/public-roadmap#138]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
I'm trying to get fake random data for API and browser checks, but I noticed that the faker library is not currently included in the node modules/dependencies.  https://www.checklyhq.com/docs/runtimes/specs/#built-in-nodejs-modules

Here is a sample test in which I was hoping to use faker:
![image](https://user-images.githubusercontent.com/11219800/127009223-84815bf0-ff86-47ca-be36-5181a89a5490.png)

**Describe the solution you'd like**
Could you please add the faker module so that we can get fake/random data for our tests?  https://www.npmjs.com/package/faker

**Describe alternatives you've considered**
I tried adding `const faker = require(faker)` to the top of my code, but when doing so I get the following error.  
![image](https://user-images.githubusercontent.com/11219800/127008835-211e56c8-e6a0-4f57-bae0-b61cdee31236.png)

If I remove the requirement above and I try to use the faker library then I get this error:
![image](https://user-images.githubusercontent.com/11219800/127009037-3ffb9909-b59d-4fd7-b812-6c7b775f3ae6.png)

**Additional context**

**Comment by tnolet** [comment]
@grob3 I like the idea! And you are correct that you cannot import arbitrary NPM modules. Have a look here for the current set of NPM modules we support  https://www.checklyhq.com/docs/runtimes/specs/#npm-packages

**Comment by brampling** [comment]
@grob3 This has been completed and is available in runtime 2021.10. See [blog post](https://blog.checklyhq.com/checkly-runtime-2021-10/) and [changelog entry](https://headwayapp.co/checkly-changelog/checkly-runtime-2021-10-with-faker-js-and-updated-playwright-214537).

**Comment by checklyalex** [comment]
Due to some circumstances outside the control of Checkly, in our latest runtime, the require syntax has changed slightly to: 

`const faker = require("@faker-js/faker")`
