### ISSUE TITLE
Feature request: Add tags to alert emails

### ISSUE THREAD

**Issue by frank1uphealth** [checkly/public-roadmap#142]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

Feature request: Our alert emails do not indicate which group they are a part of , which is where we indicate our custom accounts (based on the endpoints we're testing). The slack notifications show the tags, which we are using to list the account... so if we had the tags listed in the alert emails, that would help us immensely. 

**Is your feature request related to a problem? Please describe.**
If a problem is having to click 3+times to get the metadata/tags for a checkly alert, yes

**Describe the solution you'd like**
Add a listing of tags from a checkly check into the Alert email - like you have with the Slack notificationx

**Describe alternatives you've considered**
Updating the Check name, but tags are more reliable to identify metadata/information that's actually plugged into other systems

**Additional context**
![image](https://user-images.githubusercontent.com/79540161/129942541-fe773df5-c6c7-494d-bec1-15bb46e25ba3.png)
(want something like this in email, where Tags: are listed)

**Comment by tnolet** [comment]
@frank1uphealth this makes total sense. I'm honestly not quite sure why we don't have that already! I will make sure we add that very soon.

**Comment by clample** [comment]
@frank1uphealth thank you again for the feature request! We've added tags and group information to email alerts.
