### ISSUE TITLE
Full support for SSO authentication

### ISSUE THREAD

**Issue by AlessioCasco** [checkly/public-roadmap#145]
**Is your feature request related to a problem? Please describe.**
Problem: Be able to dynamically and seamless allow multiple users to login into checkly

**Describe the solution you'd like**
Full support of SSO providers like Okta, Google etc.

**Describe alternatives you've considered**
None

**Additional context**
n/a

**Comment by tnolet** [comment]
@AlessioCasco we already support SSO for all paid plans. We are limiting it a bit to not have a whole zoo of possible integrations but anything that talks SAML should be good to go.

https://www.checklyhq.com/docs/single-sign-on/

**Comment by tnolet** [comment]
Hey @AlessioCasco we are aware of this and have Just-In-Time (JIT) provisioning for SAML and / or SSO users under consideration. This should tackle that problem, but till we have that you indeed need to explicitly invite users.

**Comment by AlessioCasco** [comment]
Thanks for your answer, do you have any idea of when this will be supported?

**Comment by tnolet** [comment]
@AlessioCasco no hard date yet for this, sorry.
