### ISSUE TITLE
Notification trail for alerts

### ISSUE THREAD

**Issue by ragog** [checkly/public-roadmap#147]
**Is your feature request related to a problem? Please describe.**
It is oftentimes not easy to understand why a Checkly user did not receive an alert notification on a given channel.

**Describe the solution you'd like**
Exposing a notification trail to Checkly customers could be very useful. I know system like Opsgenie do that, essentially given a "paper trail" of your notifications. We would have to introduce a "notifications_sent" table which records the alert ID, the channel and the status of that notification. If a notification fails, we would also need to record the reason or error message. This is not super trivial as we would need to build this into each alerting channel.

**Describe alternatives you've considered**
As a Checkly employee, helping out users case-by-case by trying to piece together the alert trail. This is usually not trivial.

**Comment by aliasgerkw** [comment]
+1 for this feature
Recently saw one degraded event but it was not reported to slack channels or neither on email

**Comment by tnolet** [comment]
@aliasgerkw @ragog I'm closing this one if favour of the tracking issue on our roadmap  https://github.com/checkly/public-roadmap/issues/200
