### ISSUE TITLE
Feature request: port open check

### ISSUE THREAD

**Issue by james00002** [checkly/public-roadmap#155]
**Is your feature request related to a problem? Please describe.**
While checkly's existing check types do cover the majority of our needs, we also have a small number of services running non-http protocols that we have no contorl over. They can't be checked with curl. We need simple is-this-port-open checking, and it would be great to be able to do it in checkly without having to invest in some other tool

**Describe the solution you'd like**
The check should not actually make an http or https check to the port, it should just check if the port is open (similar to `nc -zv hostname portnumber` or `nmap -Pn -p portnumber hostname` or even `telnet hostname portnumber)

**Describe alternatives you've considered**
I can use some other tool like pingdom, or I can write my own code to do this check from a cloud service. Neither of those is very appealing when all of our other external checks are in checkly.

**Additional context**
Please, please, pretty-please?

**Comment by james00002** [comment]
Thank you, Tim! I have given that issue a thumbs up.

Any idea how long we might have to wait for the feature? I'm trying to figure out if I should go ahead with a temporary workaround, or just sit tight a bit longer

**Comment by tnolet** [comment]
@james00002 sorry for the late reply. I would go for a workaround right now, as it is hard for me to give any solid dates or ETA

**Comment by tnolet** [comment]
Hey @james00002 I'm closing this one in favour of the tracking ticket https://github.com/checkly/public-roadmap/issues/96
You should be able to follow its progress on the public roadmap at https://github.com/orgs/checkly/projects/4/views/4
