### ISSUE TITLE
API/Terraform support for command line triggers

### ISSUE THREAD

**Issue by nealajpatel** [checkly/public-roadmap#158]
## Context
We have been leveraging the Terraform provider to manage our check groups, checks, and alert channels. The checks have provided significant value, and with the command line triggers, we are able to integrate with our CI/CD.

However, it is cumbersome that the only way to generate a command line trigger is manually through the UI. It requires us to deploy twice to set up Checkly for a project. First, we deploy the project to create the check resources and then redeploy the project once we generate the trigger URL and add it to the CI/CD pipeline.

## Feature Request

* Ability to manage command line triggers for a checkly group/check via the Checkly API
* Ability to manage command line triggers for a checkly group/check via the Terraform Provider.

For the Terraform provider, it would be nice to optionally pass a boolean to generate the cli trigger URL and have it exposed on the resource as an attribute. Another option could be to support a data resource for the command line trigger.

**Comment by tnolet** [comment]
Hey @nealajpatel I'm tagging @ianaya89 here too. He's our core maintainer of our Terraform provider.

**Comment by ianaya89** [comment]
Hi @nealajpatel, thanks for reaching out. We are currently working on new features for the Terraform Provider:
- Public Dashboard
- Maintenance Windows

We want to support everything, so command-line triggers are something we will be tackling soon. Keep an eye on our [Public Project](https://github.com/checkly/terraform-provider-checkly/projects/1) to check TF development status and feel free to contribute or add your feedback there.

Thanks!

**Comment by nealajpatel** [comment]
Thanks for the update. Excited to see these features!

**Comment by ianaya89** [comment]
@nealajpatel we started a draft implementation for this but would like to chat with you to discuss your use cases. Do you have availability for a call during the next few days? If so, please drop me an email nacho[at]checklyhq.com to arrange it

Thanks :)

**Comment by ianaya89** [comment]
@nealajpatel we just released our first implementation of command-line triggers in TF provider. 
Take a look, would be great to hear your feedback

https://github.com/checkly/terraform-provider-checkly/releases/tag/v1.4.0-rc1

**Comment by nealajpatel** [comment]
That's great news! I will check it out and provide any feedback we have

**Comment by ianaya89** [comment]
Awesome, thanks!

BTW, We didn't implement yet the option to add directly from the check/group using a flag. We went with the resource approach now but we will add in the future that other option
