### ISSUE TITLE
Prometheus integration

### ISSUE THREAD

**Issue by tnolet** [checkly/public-roadmap#16]
Allow Prometheus users to scrape an endpoint that exposes raw Checkly metrics

_needs further exploration_

**Comment by tnolet** [comment]
First beta is pushed live today. First suggestions also coming in:

- add timing phases for API checks, i.e. wait/dns/tcp etc

**Comment by Bekt** [comment]
Saw this in passing

>add average, p95 and p99

not sure if this makes much sense for Checkly to expose since Prometheus itself would be better at this with the desired period. I can see it belonging in the API but don't see much value in the scrape endpoint.

**Comment by tnolet** [comment]
Hey @Bekt you are correct. How and on which channel (either API or Prometheus) these extra metrics will be exposed still needs to be researched. Prometheus is very much a "calculate it yourself" type of channel, where the API is more a reflection on what you get in the Checkly web application.

Any suggestions on this topic are more than welcome.

**Comment by ckoenig** [comment]
> add timing phases for API checks, i.e. wait/dns/tcp etc

Getting those additional timing phases in the Prometheus exporter would be great. Are there any plans to add those?
