### ISSUE TITLE
Support in browser checks for cypress.io

### ISSUE THREAD

**Issue by g000m** [checkly/public-roadmap#161]
I am a Cypress user. I'd love to be able to run Cypress tests on Checkly. 

According to Github, Puppeteer has twice the users, but Cypress is quite popular too.

**Comment by tnolet** [comment]
@g000m Hey, thanks for contributing. Could you edit your issue and use the template we have at https://github.com/checkly/public-roadmap/blob/master/.github/ISSUE_TEMPLATE/feature_request.md ?

I'm mostly interested in what you're using right now to run Cypress.

**Comment by tnolet** [comment]
@g000m I'm closing this ticket as we are fully committing to https://playwright.dev/ and I don't see Cypress in our future.
