### ISSUE TITLE
Readme badge for status

### ISSUE THREAD

**Issue by jerriclynsjohn** [checkly/public-roadmap#163]
**Is your feature request related to a problem? Please describe.**
I would like to see if the project is running well from my repository itself

**Describe the solution you'd like**
A clear readme badge that gives the user an idea about the status of the project.

**Comment by jerriclynsjohn** [comment]
This issue was already covered in #131

**Comment by tnolet** [comment]
@jerriclynsjohn noted! Thanks for contributing and closing the issue in reference to the existing issue
