### ISSUE TITLE
Support for TypeScript

### ISSUE THREAD

**Issue by tquid** [checkly/public-roadmap#166]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
Playwright's documentation, which is more comprehensive than on Checkly's documentation site, recommends going with TypeScript, and it has many well-known advantages for making cleaner code. I have myself to blame, but after going to Playwright's site I went with their recommendations, and returned to work on Checkly only to find out my work was not compatible.

**Describe the solution you'd like**
Support running TypeScript, please!

**Describe alternatives you've considered**
I've examined the cross-compiler, but the JS output is extremely cryptic.

**Comment by tnolet** [comment]
@tquid thanks for contributing. Typescript and the Deno runtime has our attention. However, for now it's not easy to find a native TS execution environment. Have you tried just writing checks in TS and then transpiling to JS and essentially ignoring the crypticness of the output. I think this is how 99.999% of the JS world works right now. For us it would be not very easy to support that fraction of users that wants native (non-transpiled) TS support.

**Comment by tnolet** [comment]
@tquid full TS support is now live for @playwright/test scripts. You should probably also check our new CLI on how you can drive this from your code base. https://github.com/checkly/checkly-cli
