### ISSUE TITLE
Support for @playwright/test

### ISSUE THREAD

**Issue by tquid** [checkly/public-roadmap#167]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
We use similar tests in our github workflow to what we use in Checkly and would like to have just one codebase for tests, to avoid duplicating effort or having to downgrade the features already in use with the github workflow.

**Describe the solution you'd like**
Ideally support fixtures, page object models, and the like as offered by Playwright. I could see this being done by parsing out the `test` stanzas in typical Playwright code as individual tests, or, if keeping them as individual files, running the equivalent of `npx playwright test` against each file.

**Describe alternatives you've considered**
Alternatives require us to effectively re-architect our testing framework if we want to have compatibility.

**Comment by tnolet** [comment]
@tquid this has our attention. The main challenge here is abstracting between the various `.spec.js` files, their various dependencies and our per check, per region stateful runtime. We've essentially been chewing on this problem for 12 months on and off. We are Jest and PW users ourselves and it works great in CI. But you want it to work during production, from multiple regions.

However, it seems like a golden opportunity to pick your brain here so I will reach out outside or GH for a possible chat.

**Comment by darkostanimirovic** [comment]
Hey everyone, just a quick update that we've started working on the first iteration to integrate PW tests natively.

If you're interested in joining the preview once it's ready, shoot me an email at darko at checklyhq dot com or ping us via Intercom.

**Comment by Pondorasti** [comment]
Very exited for try this out! 🤗

**Comment by darkostanimirovic** [comment]
Hey everyone! We're ready to add people to the early technical preview. 😍 

There are some temporary caveats of course:
1. If you have more than a few test cases, it seems like you need to close pages after every test or the check keeps failing.
2. No TS support yet, but we're on it!
3. No trace files yet. This is on our radar for September.
4. At this moment overriding context permissions won't work. We're aware of it and are working on a fix.

Most of these will be fixed or improved. Our goal is to have a frictionless PW test support at the end of Q3. You can help too, by testing it out with a lot of different tests, and sharing feedback.

Let me know if you want to give it a shot – send me your account ID or email at darko at checklyhq.com

**Comment by jan-osch** [comment]
I'm happy to announce that we have shipped our native `@playwright/test` integration available for all our customers 🎉
If you are interested in the details [here is the demo session on YT that we did yesterday](https://www.youtube.com/watch?v=mB-jIkLlY24). You can find an overview of available features and known limitations in [our docs](https://www.checklyhq.com/docs/browser-checks/playwright-test/).  
 
Of course we are still curious about your feedback 😉
