### ISSUE TITLE
Check moves between Groups can cause accidental alerts

### ISSUE THREAD

**Issue by cpressland** [checkly/public-roadmap#168]
**Is your feature request related to a problem? Please describe.**
When using the new "Move to Another Group" feature, if a check uses a variable such as `{{GROUP_BASE_URL}}` which is missing in the new group, the check goes into a failure state.

**Describe the solution you'd like**
The check should move into an "invalid" state instead of a "failed" state, or, a validation check should be performed and the move should be blocked.

**Describe alternatives you've considered**
None.

**Additional context**
N/A

**Comment by tnolet** [comment]
@cpressland thanks for reporting. This is indeed a good insight. We actually disable checks automatically when removing them from groups for this exact reason. We will have a quick look what makes sense here.

**Comment by maxigimenez** [comment]
@cpressland We released a change regarding this functionality, as Tim mentioned above we are deactivating the check once is removed from a group, for UX consistency we introduced the same logic on the move modal, so when moving a check within groups this will be deactivated. Once again thanks for reporting this!
