### ISSUE TITLE
Add more / different metrics to public dashboard for more balanced view

### ISSUE THREAD

**Issue by tnolet** [checkly/public-roadmap#17]
Currently, we report the 24h ratio on the public dashboard. This number can be unforgiving when not seen in context of other, longer running, metric. We should add:

- 7 day or 30 day ratios.
- longer running / all time ratios,

![image](https://user-images.githubusercontent.com/3802923/52412902-64946b00-2ae0-11e9-9f47-7164e363612e.png)

**Comment by fproulx-eoscanada** [comment]
Thank you 👍 this is much needed

**Comment by tnolet** [comment]
Looking at future expansions, it would make sense for users to be able to select which metrics are visible. This can be initially done via simple select inputs. I.e.

- [ ] 24h ratio 
- [ ] 7d ratio
- [ ] avg resp. time
- [ ] 99p resp. time

**Comment by tnolet** [comment]
Initial release will have 
- 7d ratio
- collapsed buttons in a "more" popover
- In general more economic handling of screen real estate for future addition of extra metrics

![image](https://user-images.githubusercontent.com/3802923/52625030-65e2e080-2eb0-11e9-8339-476d5db13c9e.png)

**Comment by Kikobeats** [comment]
IMHO, a good addition would be used P95 over avg response since it normally reflects a more realistic value

![](https://pbs.twimg.com/media/D53omBaW0AAdty9.png)

**Comment by tnolet** [comment]
https://github.com/checkly/product-roadmap/issues/39

**Comment by CharlieMc0** [comment]
+1 I'd love to see P95 on the public dashboard so it matches the internal screen.

**Comment by ianaya89** [comment]
@CharlieMc0 @croaky we are on it 🙌

**Comment by tnolet** [comment]
closing this ticket!  See
- https://www.checklyhq.com/docs/dashboards-v2/
- or hack your own dashboard with https://www.checklyhq.com/docs/analytics/
