### ISSUE TITLE
pull from github on push and pull then run the latest e2e suite from multiple probes

### ISSUE THREAD

**Issue by ivelin** [checkly/public-roadmap#174]
Currently, checkly requires e2e tests to be kept in its web site, separately from a typical project's e2e test location in a git repo.

Would be great if there is an option that works like Netlify Deployment Preview or Fleek Deployment Preview.

1. Use exactly the same e2e build and test script `yarn test:e2e` that we use for local dev and github CI.

2. As soon as a PR is created , ChecklyHQ checks out the latest e2e testsuite from github and runs it from all configured locations around the world to provide performance assessment of the incoming PR code. Consequently after a PR merge, ChecklyHQ picks up the latest e2e testsuite pushed to github and schedules runs from its location around the world until the next github push.

**Comment by tnolet** [comment]
@ivelin thanks for contributing. We have looked at this use case A LOT. We get question about it essentially every week. The devil is always in the details. I would love to chat with you about this, but let's start with some initial questions:

1. Do you expect the test suite you run to be persistent? i.e. it tracks performance over time, implying some state on our side.
2. Or, do you see this more as an ad hoc smoke test, where Checkly functions as a global, parallel engine that gives you the option to see if whatever set of checks you have in your code base work right now?

**Comment by tnolet** [comment]
tagging @umutuzgur and @brampling

**Comment by ivelin** [comment]
> @ivelin thanks for contributing. We have looked at this use case A LOT. We get question about it essentially every week. The devil is always in the details. I would love to chat with you about this, but let's start with some initial questions:
> 
> 1. Do you expect the test suite you run to be persistent? i.e. it tracks performance over time, implying some state on our side.
> 2. Or, do you see this more as an ad hoc smoke test, where Checkly functions as a global, parallel engine that gives you the option to see if whatever set of checks you have in your code base work right now?

Thank you for looking into this. Good questions. Thoughts below:

Ideally on PR, we would like to be able to see what the delta is between the most recent performance report from before the PR and after the PR changes. A simple example would be to see the `lighthouse` score before and after.

However on push to the deploy branch, we would like to see checkli update its agents to run the latest committed e2e testsuite from the point of push onward. At a minimum alerts would be great. Eventually a timeline with performance improvement or degradation would be also useful.

Hope this helps. Thank you!

**Comment by tnolet** [comment]
@ivelin This helps. Some more questions arise though. 

1. How would you manage all the check settings like run frequency, locations, environment variables etc.?

2. Are you also using API checks and would you also run them from Git?

**Comment by ivelin** [comment]
More good questions I haven't thought about :)

Random thoughts below:

> @ivelin This helps. Some more questions arise though.
> 
> 1. How would you manage all the check settings like run frequency, locations, environment variables etc.?

Maybe a yaml file in the repo for config settings that are safe to be in the public?
Env vars could be managed via admin secrets section in the chekly app similar to how github and gitpod manage env secrets.

> 2. Are you also using API checks and would you also run them from Git?

For our case, we would start with `lighthouse` then add custom puppeteer (or playwright) e2e tests. 

Eventually we may add API test suite as well, although we are currently using `insomnia` for graphql and REST API tests. Not sure if checkly plans on supporting it.

**Comment by tnolet** [comment]
@ivelin on your remark for `lighthouse`. We do not have a Lighthouse check and would also not recommend running it on Checkly right now (even if it were possible). Lighthouse is very resource intensive and requires a bigger, more heavier infrastructure than we provide right now.

**Comment by tnolet** [comment]
@ivelin we shipped our GitHub sync feature to public beta yesterday. It should solve a big part of your use case. Check our docs and blog here:
- https://www.checklyhq.com/docs/browser-checks/github-code-sync/
- https://blog.checklyhq.com/github-browser-check-synchronization-goes-into-public-beta/

**Comment by ivelin** [comment]
> @ivelin we shipped our GitHub sync feature to public beta yesterday. It should solve a big part of your use case. Check our docs and blog here:
> 
> * https://www.checklyhq.com/docs/browser-checks/github-code-sync/
> * https://blog.checklyhq.com/github-browser-check-synchronization-goes-into-public-beta/

Fantastic. Will take a look!
