### ISSUE TITLE
UI confusion with text body assertion

### ISSUE THREAD

**Issue by wolfgang42** [checkly/public-roadmap#175]
I just spent my first 10 minutes using Checkly in a state of confusion, so here's a bit of feedback from a brand-new user. (This isn't a feature request *per se,* but I figured it might be useful to hear.)

**Is your feature request related to a problem? Please describe.**

Presented here in narrative form:

I'm setting up my first API check. I've filled in the HTTP request options, skipped over the setup/teardown scripts, and am deciding on assertions. I want to make sure I'm serving actual content by checking for a representative phrase, so I pick "Text body" as the source. I see that the property is a regular expression, so there I fill in the text that I expect to match. Next there's a dropdown, from which I pick "Contains" since that's what I want to check the body text for. (I'm not sure what it would mean for my body text to be "less than" my phrase, but I certainly don't want e.g. "equals" since it's only part of the body, nor "is empty" since I do expect there to be a response.) Since I've now set up my condition, my eyes skip briefly over the last field before moving on to the next section.

When I get to the bottom of my form and run my check, it tells me my assertion has failed. Apparently, it thinks the body does not contain my text—even though I can see it *right there* in the response that's shown just above.

After some head-scratching (does it not like that the content-type is HTML? have the spaces confused it somehow?) I consult the documentation and discover that it's not "[body text] [contains] [property]", but rather "[property].match([body text]) [contains] [target]". With this knowledge I construct a working assertion, though it still feels a bit awkward to write `/(.*)/ contains "Phrase"`.

**Describe the solution you'd like**
Seems like there's a UI tweak to be had here. My best suggestion is to add another comparison, “is matched/is not matched” which disables the Target field and just checks the regular expression without capturing. Having that comparison in the list might make it clearer that the other options carry on into the next field.

**Comment by tnolet** [comment]
@wolfgang42 thanks for this. This seems very backward indeed. Either we should go with your proposed solution or skip the whole regex part and allow you to just select the "contains" option and we implicitly do a `/(.*)`.

**Comment by tnolet** [comment]
This seems such a basic case I will earmark it and put into our public roadmap

**Comment by tnolet** [comment]
@wolfgang42 I think your use case can be drastically simplified by just skipping the regex. This is already working right now.

![image](https://user-images.githubusercontent.com/3802923/151542113-9c2c3303-401d-4ea8-b389-59fde5c23b9b.png)

**Comment by tnolet** [comment]
@jenya-II can you have a look at how we can be clearer that the regex option for properties is totally optional here?

**Comment by wolfgang42** [comment]
That is much simpler, thanks!

My first thought is to just stick a note that says "optional" on the field:

![Screenshot of the assertion UI, with "Optional, defaults to all body text" in small text under the regex field](https://user-images.githubusercontent.com/2261204/151591369-bcc4a522-af68-4c23-888f-cab6ee254b66.png)


...but I'm sure there's a more elegant way to make this clear.

**Comment by tnolet** [comment]
Boom! Thanks @wolfgang42! Schönen Feierabend!

**Comment by miliberlin** [comment]
@wolfgang42 We have included a hint message in our app now. Thanks a lot for taking the time to document your issue!

**Comment by wolfgang42** [comment]
Yay! It looks much clearer now.

![image](https://user-images.githubusercontent.com/2261204/152092160-98c88b73-6a39-438a-9e59-dc4515c661b0.png)

Thanks for giving me a place to document my problem!

**Comment by wolfgang42** [comment]
Following up on this, the text seems to have gotten lost somehow? I just went to set up another check and experienced exactly this same confusion again.

**Comment by miliberlin** [comment]
@wolfgang42 we are constantly trying to improve Checkly and this unfortunately seems to have gotten lost during refactoring. I'll take a look today. Thanks for reporting it (again) 😊

**Comment by miliberlin** [comment]
@wolfgang42 It's back now, thanks for letting us know 🙏
