### ISSUE TITLE
Allow us to specify if dashboard tags are `or` or `and`

### ISSUE THREAD

**Issue by peter-dolkens** [checkly/public-roadmap#176]
**Is your feature request related to a problem? Please describe.**
We're a SaaS provider, and I want to be able to manage checks for multiple clients at once - potentially with a bulk billing option.

Right now, if I create a single team, and start tagging `client-1`, `client-2`, `client-3` then I can easily create a dashboard and filter to `client-1`.

If I then introduce an extra tag for environments `env-live`, `env-test`, `env-dev` then it's not currently possible to create a dashboard or maintenance window for `client-1 live` because dashboard tag filtering is `OR` not `AND`.

**Describe the solution you'd like**
I want to be able to make a dashboard that is `partner: x` AND `environment: y` AND `service: z`

**Describe alternatives you've considered**

I could add another tag, `client-1-live`, but that will get extremely cluttered, especially as we build up a rich library of tags. Currently we have `scope`, `environment`, `partner`, `service` and `payload` tags, which we may want to combine to, for example, `find all production tests that use graphql` or `find all public-facing tests for big-partner`

I could create a new account/team (we already have a monitoring/alerts email address, so this somewhat makes sense actually) but this feels like double-dipping on free quota.

**Additional context**
I don't think we need full flexibility to choose `AND` / `OR` for every tag. Simply being able to specify if the dashboard/window uses `AND` logic or `OR` logic would suffice (so existing dashboards/windows can be flagged as `OR` for backwards compatibility)

You *could* go into a complex expression builder, but that's certainly not MVP.

**Comment by tnolet** [comment]
@peter-dolkens thanks for reporting. I 100% understand the request. I have no clear ETA or for such a feature, but will check the feasibility of this.

**Comment by tnolet** [comment]
@peter-dolkens we are adding this feature to the scope of the upcoming functional changes to the dashboards. See https://github.com/checkly/public-roadmap/issues/238

**Comment by tnolet** [comment]
@peter-dolkens this just shipped and is live on Production
