### ISSUE TITLE
Prometheus tag label feature request

### ISSUE THREAD

**Issue by james00002** [checkly/public-roadmap#182]
**Is your feature request related to a problem? Please describe.**
The prometheus integration lumps all tags into a single label in a comma separated list. These can be matched with regex pattern matching, but this isn't how prometheus labels are best used.

**Describe the solution you'd like**
If a tag is created in the format "key:value" then instead of including it in the tags label for prometheus, split it out to a separate label using the key name

For example, if a check has a tag `project:foo` then instead of exporting it to prometheus as `tags="othertag,project:foo,yetanothertag"` export it as: `project="foo" tags="othertag,yetanothertag"

**Describe alternatives you've considered**
I have considered writing my own proxy for the checkly prometheus endpoint that would parse the tags label and split out key:value pairs

**Comment by tnolet** [comment]
@james00002 thanks for reporting. I was not aware that the `key:value` tagging pattern is common for Prometheus. Is this the case, e.g. is this a "native" Prometheus feature?

**Comment by james00002** [comment]
I don't know how widespread key:value labels are among checkly users, only that we use that format a lot for our own checks.

For prometheus, yes it is a best practice to avoid merging multiple values into a single label. combining them all in a comma separated lis with the label name "tags" is better than nothing-- this is just an idea for a possible improvement

`key:value` isn't a standard or anything. Prometheus labels are normally in the format `key="value"` but that would look weird as a checkly tag

**Comment by tnolet** [comment]
@ianaya89 let's have a look at this. Seems like a quick win

**Comment by ianaya89** [comment]
@tnolet I took a look and will be something quick to implement. We will be working on this during next week

**Comment by tnolet** [comment]
@james00002 we are planning to release this. Follow this space.

**Comment by ianaya89** [comment]
Hey @james00002 
This improvement is already live. Give it a try and let me know about any possible feedback :)
