### ISSUE TITLE
Alert recipient which is not auto-enabled for new groups

### ISSUE THREAD

**Issue by philpennock** [checkly/public-roadmap#183]
**Problem:**  
We have a few alert recipients.  One of which is our CEO, who cares about a particular project which is his, and who _might_ need to sometimes be enabled as recipient of last resort, but who should not be enabled by default.

We're currently configuring manually through the web UI, as we get a feel for the features and tooling available: moving too soon to Terraform without an adequate mental model would lead to a lot of wasted engineering time.  So our options are strictly what the web UI allows us to configure.

At present, any alert recipient can be disabled for existing groups, but if new groups are created (and maybe new alerts outside a group) those recipients will be enabled by default for the new items.  So our CEO will keep getting enabled-by-default unless people remember to disable him.

**Solution desired:**  
Ability to mark an alert recipient as "present as an available target, but not enabled by default".

This would let us do things like create prod-alerts and dev-alerts recipients and choose to only enable the prod alerts for groups which manage services in full production readiness.  And keep the CEO from being opted-in-by-default to every new group.

**Alternatives considered:**
We could move to Terraform immediately, but that would preclude learning and mean that we couldn't let other people just add checks easily.  My longer-term goal is to import state into Terraform later, and be able to restore as needed (and maybe lock some groups out from web modifications?) but to still allow non-devops people to create monitoring for their projects without having to learn Terraform.

**Comment by tnolet** [comment]
@philpennock I understand your request, but I'm afraid that complicating our alerting channel logic for this request is not high on the list. Maybe an option is for your CEO to create a custom dashboard on a hard to guess URL so he/she can keep tabs? Another option is to go for a more flexible alert routing solution like Pagerduty or Opsgenie. We integrate with both. We use Opsgenie and have a similar routing logic there that me (CTO) and our CEO get alerted when all on call engineers fail to respond after a while.

**Comment by philpennock** [comment]
Yeah, we're integrating to OpsGenie already, but this is primary service owned by the CEO as the _first_ point of contact.  I will see if I can inspect the inbound event in OpsGenie to duplicate the structure from Checkly and re-route into a different notification queue.
