### ISSUE TITLE
Tags propagation to OpsGenie

### ISSUE THREAD

**Issue by philpennock** [checkly/public-roadmap#184]
**Is your feature request related to a problem? Please describe.**
Implementing the workaround suggested in #183 I hit a roadblock because tags from Checkly are not propagated into OpsGenie.

**Describe the solution you'd like**
The union of tags defined on an alert and tags defined on the group of an alert should be propagated to OpsGenie as tags in their alert API.

**Describe alternatives you've considered**
* Routing alerts in Checkly itself, which has full context, but doing this without notifying special-case recipients for all new groups was closed in #183 (which used one current example)
* Filtering based on some other attribute in OpsGenie, but they only support filtering on Priority and Tags.
* Multiple Checkly accounts

**Comment by tnolet** [comment]
@philpennock sorry for the late reply. This looks like a good contribution. Thanks for reporting.

**Comment by tnolet** [comment]
@philpennock this is live now!
