### ISSUE TITLE
Support Playwright 1.20 and Puppeteer 1.13

### ISSUE THREAD

**Issue by tnolet** [checkly/public-roadmap#188]
As per our runtime policy, we aim to release PW 1.19.x support and PPTR 1.13.x support in Q1 2022.

https://www.checklyhq.com/docs/runtimes/#how-we-update-and-release-new-runtimes

**Comment by tnolet** [comment]
This is now in BETA on our own production environment. Targeted release date is Monday 21 March

**Comment by tnolet** [comment]
Small update here, we found some bugs and the release is a bit delayed. We have moved to supporting 1.20. Target release date is moved to first week April

**Comment by frontsideair** [comment]
It would be really nice to bump Playwright to 1.21, as it now has (experimental) [aria selector support](https://playwright.dev/docs/release-notes#highlights). I like to write my tests using accessible selectors to avoid depending on test ids, classes or tag names.

Selecting by text works most of the time, but can be brittle if the text appears in multiple places. My current workaround is selecting by accessible tags, but I'd much prefer selecting by roles instead to make the tests durable.

**Comment by tnolet** [comment]
@frontsideair hi, we are deep in testing 1.20 still. It's taking a bit longer than expected sadly. Also, the PW team is going very very fast 😅 (this is a good thing!)

**Comment by tnolet** [comment]
This was released this week. Took a while 😅 as we hit some snags.
