### ISSUE TITLE
Jest integration

### ISSUE THREAD

**Issue by tnolet** [checkly/public-roadmap#19]

**Comment by tnolet** [comment]
For this following this ticket. We already introduced the `expect` package earlier this month. You can now use the familiar expect statements in all assertions in browser checks and setup/teardown scripts.

**Comment by mehdi559914** [comment]
> برای این دنبال این بلیط. ما قبلاً `expect`بسته را در اوایل ماه جاری معرفی کردیم . اکنون می توانید از عبارات انتظار آشنا در همه ادعاها در چک مرورگر و اسکریپت های setup / teardown استفاده کنید.
https://github.com/checkly/public-roadmap/issues/19#issuecomment-804913179

**Comment by tnolet** [comment]
Closing this issue. A dedicated Jest runner environment is under consideration, but the `expect` library should cover many needs. On the Checkly side we made this the default in all of our examples and recommendations.
