### ISSUE TITLE
SOC 2 compliance

### ISSUE THREAD

**Issue by tnolet** [checkly/public-roadmap#190]
We want to achieve SOC2 compliance by the end of 2022. We are driving an internal project to go through the stages of preparation, audit and eventual compliance. 

Key outcomes are:
- Clearer security stance 
- Easier security questionnaire procedures
- Reduced procurement time for Enterprise customers

**Comment by hlenke** [comment]
We have started the process and aim to be SOC 2 compliant by the end of 2022.

**Comment by hlenke** [comment]
I've great news. 🎉 Checkly is now SOC 2 Type 1 complaint showing we cover security, availability, confidentiality, privacy, and processing integrity. We are now in the process of completing SOC 2, Type 2 compliance.

**Comment by hlenke** [comment]
We have completed this initiative and are now SOC 2 Type 2 compliant! 🎉

Please join our launch week session on March 2, 2023 – at 9 AM PT / 12 PM EST / 6 PM CET to hear more. You can find the link here: https://www.checklyhq.com/launch-week/

Also, please get in touch with security@checklyhq.com if you have any questions.
