### ISSUE TITLE
Support selectors from testing-library

### ISSUE THREAD

**Issue by Svish** [checkly/public-roadmap#193]
**Is your feature request related to a problem? Please describe.**

Checks involving interaction with forms and buttons can often be janky because, depending on the site, it can be difficult to write stable selectors for fields and buttons.

**Describe the solution you'd like**

Support the utilities and selectors from the [Testing Library](https://testing-library.com), which has very good ways of selecting for example input-fields based on their label, buttons based on their accessible name, and so on.

**Additional context**

The library already has official support for Puppeteer, so potentially it should just be a matter of allowing us to import the utilities from the `pptr-testing-library` package when writing checks with Puppeteer:  
https://testing-library.com/docs/pptr-testing-library/intro

**Comment by Svish** [comment]
No, because I started with these tests locally, and Playwright doesn't have testing-library integration (from what I can find, at least not officially). Looked at it now, and doesn't look like Playwright have similarly helpful accessibility-based selectors to those found in testing-library.

**Comment by tnolet** [comment]
@Svish we shipped support for @playwright/test 1.28.0 a while ago. This has support for Testing Library selectors. We are using today everywhere!
