### ISSUE TITLE
Alerting Reliability Enhancements

### ISSUE THREAD

**Issue by tnolet** [checkly/public-roadmap#200]
We have some snags regarding alerting that impacts the trust Checkly users have on our alerting. 

1. Degraded states moving to failures and/or recovery states are sometimes confusing. See internal tickets [1658](https://app.shortcut.com/checkly/story/1658/alert-degraded-recovery-alerts-sent-despite-check-settings), [1723](https://app.shortcut.com/checkly/story/1723/rethink-remove-escalation-switch-for-degraded-failure-events) and [122](https://app.shortcut.com/checkly/story/122/degraded-checks-should-also-take-into-account-escalation-settings)

2. Users sometimes miss alerts due to configuration issues, expired tokens or other issues that are not easy to prevent from a UX perspective or validation perspective. A token for Opsgenie might expire, a Slack channel might be removed.  We want to always notify owner and admins by email when a notification fails on any channel.

3. To triage and debug any alerting issues, we want to show a simple alert notification trail to shows for each alert which notifications were send out and — where applicable — if they were received by the corresponding integration.

4. When I add an alert notification channel to an already failing check, I want to be alerted directly and not wait for a state transition to happen.

**Comment by tnolet** [comment]
References https://github.com/checkly/public-roadmap/issues/147

**Comment by danielpaulus** [comment]
Little note on 2. 
We currently start free plans with 0 SMS included. Which cause your alert to fail silently. From a customer's perspective everything is configured correctly, just the alert is never received as we never indicate anywhere that the plan limit was "reached".

**Comment by tnolet** [comment]
https://github.com/checkly/public-roadmap/issues/226

**Comment by tnolet** [comment]
We solved numbers 2 and 3 of this ticket and these features are live now. We deprioritized number 4. The tickets in 1 are still open and will remain open.
