### ISSUE TITLE
Private locations support in API and Terraform

### ISSUE THREAD

**Issue by brampling** [checkly/public-roadmap#212]
We are adding support for private locations in the Checkly public API and the Terraform provider. This includes:

- add, remove locations
- add, remove API keys
- assign checks to private locations

**Comment by ianaya89** [comment]
This was shipped, you can now use Private Locations with:

- [Public API](https://developers.checklyhq.com/)
- [TF provider](https://registry.terraform.io/providers/checkly/checkly/latest/docs) v1.6.0
- [Pulumi provider](https://www.pulumi.com/registry/packages/checkly/) v1.1.0
- [Go SDK](https://github.com/checkly/checkly-go-sdk/releases) v1.6.1
