### ISSUE TITLE
Store Check code on GitHub beta

### ISSUE THREAD

**Issue by tnolet** [checkly/public-roadmap#213]
# Problem statement
Developers need to synchronize browser check scripts from their own code repositories into Checkly browser checks.

Currently they run tests locally during application development, then have to copy and paste updated check scripts into Checkly browser checks. This causes additional work, the possibility of error when migrating the script, and the possibility of monitoring failures of the updated application.

Enabling developers to use the same check script in their local development and testing processes and their production Checkly monitoring allows them to feel confident creating more checks in Checkly and tying Checkly closer to their development processes.

# Success Metrics

- number of checks syncing code - We can track the aggregate number of checks using the script sync as an adoption metric
- number of checks created by accounts using the feature - We can track the before/after number of checks for each account that adopts the feature. The checks created using the feature can be attributed as expansion revenue.

# Business Case

Check script synchronization will allow developers to use Checkly in more parts of their workflow. This will increase the number of check runs by users who adopt this feature. In addition Checkly will become more tightly coupled to the users’ workflows and infrastructure which increases retention and reduces churn.

# Scope

- We are only targeting Browser Checks (Playwright, Puppeteer / Node.js)
- We are only targeting GitHub as CVS provider

**Comment by tnolet** [comment]
This issue replaces this one as the top level tracking issue  https://github.com/checkly/public-roadmap/issues/174

**Comment by rlevy-byway** [comment]
Definitely want this. It will help with adoption of Checkly if we can avoid "double-keying" of tests

**Comment by msafi** [comment]
Nice, look forward to it!

**Comment by tnolet** [comment]
Hi folks, we just moved this feature to public beta and it's accessible to all users. 

- docs are here https://www.checklyhq.com/docs/browser-checks/github-code-sync/
- new discussion topic is here https://github.com/orgs/checkly/discussions/3
