### ISSUE TITLE
Private Locations API check proxy server support

### ISSUE THREAD

**Issue by brampling** [checkly/public-roadmap#216]
Private locations currently support proxy server configuration for the agent to management API connection and for Playwright and Puppeteer browser checks run within the private location.

We are adding support for running API checks through a proxy server within a private location for users who have that configuration internally. You will be able to specify the proxy server and store credentials securely in environment variables.

**Comment by tnolet** [comment]
This feature has now shipped. Have a look at our docs https://www.checklyhq.com/docs/private-locations/proxy/
