### ISSUE TITLE
For a retried request, expose the first attempt failure logs

### ISSUE THREAD

**Issue by aliasgerkw** [checkly/public-roadmap#217]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
This check failed in retry request, is it possible to find out what was the failure in first attempt - https://app.checklyhq.com/checks/f9826520-be69-4c24-b941-4fdc3447606e/results/api/adb39a45-0308-4274-bd6f-aecc4aa502d9

**Describe the solution you'd like**
I feel consumer should be aware of what has made the first attempt failed in case there is any

**Describe alternatives you've considered**
None

**Additional context**
NA

**Comment by tnolet** [comment]
@aliasgerkw this would be a good upgrade, I'm tentatively adding this to our larger initiative on tweaking some alerting and results logic.

https://github.com/checkly/public-roadmap/issues/200

**Comment by drakirnosslin** [comment]
@aliasgerkw - Hey, I just wanted to let you know that we've started working on this, & have the first iteration of the design ready & would appreciate it if you could look at it & let us know what you think.

 The flow is available here: [https://t.maze.co/154564376 ](https://t.maze.co/154564376 )

Cheers!

**Comment by aliasgerkw** [comment]
Thanks @drakirnosslin looks good.

**Comment by aliasgerkw** [comment]
<img width="1365" alt="Screenshot 2023-05-02 at 12 18 59 PM" src="https://user-images.githubusercontent.com/51911147/235598618-e7aeef8b-6781-4619-adcb-92e623e3b373.png">
<img width="1325" alt="Screenshot 2023-05-02 at 12 20 03 PM" src="https://user-images.githubusercontent.com/51911147/235598862-83ccd1d3-2ea0-4793-b5a5-c29c37653b45.png">

@drakirnosslin Hey Rikard, I enabled beta but can only see Attempt 2 in all failures. Not getting Attempt 1 tab as mentioned in screen shot of change logs.

**Comment by drakirnosslin** [comment]
Hey @aliasgerkw - Results for both attempts will only be available for future check runs as we didn't store result data for the initial run before so there's nothing to fetch. If you trigger a run that has the 'double check on failure' & is set to fail you should get a run with two results back.

Let me know if that doesn't work!

**Comment by aliasgerkw** [comment]
Hey @drakirnosslin this looks good.
<img width="1310" alt="Screenshot 2023-05-05 at 12 55 52 PM" src="https://user-images.githubusercontent.com/51911147/236399366-8de62128-f66a-4954-a31f-37cb539b2b19.png">

Thanks team for considering this request.

**Comment by drakirnosslin** [comment]
@aliasgerkw
Hey Aliasger, happy you think so!

Thanks for the feedback; we're retrying from a different location to avoid false positives due to network outages between the location & the test target or other issues with the location itself.

Could you explain a bit more why you'd like to retry from the same location?

Cheers, and have a great weekend!

**Comment by aliasgerkw** [comment]
Got it, avoid false alarm is also fine. 
I am good with it. Thanks for clarification.

**Comment by tnolet** [comment]
@drakirnosslin please move this to done
