### ISSUE TITLE
More reports customization options

### ISSUE THREAD

**Issue by philippeauriach** [checkly/public-roadmap#218]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
I need to provide clear reports every two months, showing incidents among normal times

**Describe the solution you'd like**
I'd love to see the incidents more proeminently displayed on the "reports" graphs: today a day with a success rate of 99,87% (1 error in the day) is almost indisctive of a day with 100%.

I know that creating a chart that is convenient for every use case is impossible, so I think having the option of downloading a csv would be enough, as everyone could create their own charts from it. 

The csv could contain one row per day, and for each row:
- the day
- name of the check
- number of successful attempts
- number of failed attempt
- percentage
- performances

**Describe alternatives you've considered**
Inspecting the console/network tab, copy pasting the json answer from the checkly api request, transforming it into csv, generating my own chart from it with a bigger delta so we can see the difference between 99,9% and 100%. But that doesn't solve the problem of marking incidents, I need the precise incident list

**Comment by philippeauriach** [comment]
Hello @darkostanimirovic ! This would definitely help and be a quick win to visualize days that are not « 100% ». This could be a checkbox « align to zero » for example. 

But in the end, having a csv would let us be in complete control of the output, in our case we must show reports to an institution, and therefore need to adapt to some style guidance. 

But having the first option would definitely help! 

Thanks for your answer,

**Comment by darkostanimirovic** [comment]
Have you tried using our API for this? You mentioned that you have, but can you elaborate on the shortcomings?

When you say "I need the precise incident list" do you mean the daily aggregations or the individual check runs?

**Comment by philippeauriach** [comment]
Daily aggregation could be enough, but all individual check runs would be perfect. 

I did not try the API, I used the debugging console in chrome to inspect api calls made by the dashboard. Is there any documentation on checkly API ? I have no problem using it if it gives access to the data !

**Comment by tnolet** [comment]
@philippeauriach all our API docs are at https://developers.checklyhq.com/

**Comment by philippeauriach** [comment]
@tnolet thanks a lot ! The `check results` and `check results (rolled up)` look exactly like what I wanted.

I'll try that for our next report !

**Comment by philippeauriach** [comment]
Except that the "check-results-rolled-up" will be deprecated early July. What is the preferred way ? Calling "check-results" regularly and saving the data on our side ?

**Comment by tnolet** [comment]
@philippeauriach it really depends on what you want to do. 

1. I would start with the `/v1/reporting` endpoint. It aggregates the data for you, like the deprecated `check-results-rolled-up` endpoint, but `/v1/reporting` is much more granular.
2. `/v1/check-results` is for accessing individual results mostly is for that reason a lot more detailed.

Can you give us some insights into exactly what you want your reporting data to look like?

**Comment by philippeauriach** [comment]
I'm not sure yet, but I think the end result would be, ideally, a chart a bit like the one you mentioned (with the chart starting at the minimum), and above it a mention where errors occurred. I think we will try next month with the API to generate the chart, and add the number of failed events manually.

thanks,

**Comment by tnolet** [comment]
@philippeauriach we just shipped a new `/v1/analytics` API that should get you a ton of options to pull data from Checkly and generate reports. We found that us building a reporting engine that fulfils all needs was very hard. So we just give you the data and you can roll your own. We have some examples in https://www.checklyhq.com/docs/analytics/
