### ISSUE TITLE
Visual feedback when a check is manually launched during a maintenance period

### ISSUE THREAD

**Issue by julienlafont-tabmo** [checkly/public-roadmap#219]
**Is your feature request related to a problem? Please describe.**
I was working on a check yesterday. My usual workflow is to push a teardown script, run one of the checks, and see the result.

But suddenly running any check didn't work anymore.
 - If I run it manually, the button is renamed to "Running", a small square is added in the timeline, but the UI stays like that forever.
 - If I run a "run group", nothing happens. I see the "last run: a few seconds ago", but nothing where I can see the result.

I spent 1 hour looking for why my checks were not working anymore, looking for a problem in my script...
It turns out that the checks were not executed because I had a **maintenance period active** which automatically activated in the middle of my tests

**Describe the solution you'd like**
There should be clear visual feedback if a run is not executed because a maintenance period is active.

The UI should either display an explicit message or prevent the run from being executed.

OR, only automatic runs should be affected by the maintenance period, not manual runs (I see many use cases where it would be interesting to run the checks manually, to make sure that a commit did not create regression during an update, before closing the maintenance for example)

**Comment by tnolet** [comment]
@orcunilbeyli @kiroushi we should add a small banner or similar to the top across the whole app that a maintenance window is active. Javier already had a small proposal. Ideally, the banner would show the name of the maintenance window.

**Comment by chocolateofpain** [comment]
@julienlafont-tabmo we now shipped an improvement around this topic: a banner will alert any user of an upcoming or ongoing Maintenance window, with a link to edit the window if they wish to do so. 
Thanks again for the feedback !
