### ISSUE TITLE
Ability to see both failed checks

### ISSUE THREAD

**Issue by IanWhitney** [checkly/public-roadmap#226]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
No. This is more of an improvement.

**Describe the solution you'd like**
When I have a check that has "Double check on failure" enabled, I would like to be able to see both failed checks. Currently I can only see one of them, and I'm not sure which one it is.

**Describe alternatives you've considered**
I don't know of any alternatives in Checkly

**Additional context**
We had a check that would fail with an extremely slow response time. And I wanted to be able to see if _both_ checks had failed with the same extremely slow response time or not. Being able to see this would help our investigation effort.

**Comment by tnolet** [comment]
@IanWhitney thanks for reporting. We will start supporting this.

**Comment by tnolet** [comment]
@IanWhitney we are starting to work on this start next month (March '23)

**Comment by tnolet** [comment]
Sorry, another update. We are closing this ticket in favour of https://github.com/orgs/checkly/projects/4/views/4?pane=issue&itemId=21239294
