### ISSUE TITLE
API - Option to allow API requests without API token

### ISSUE THREAD

**Issue by heipei** [checkly/public-roadmap#227]
**Is your feature request related to a problem? Please describe.**
I would like to request the Check Status for my public dashboard via an API to display the metrics in my own SPA. I do not want to link to or in any way include "official" Checkly pages, badges, iframes etc.

**Describe the solution you'd like**
An option to allow public API requests without authentication for the public checks on my dashboard.

**Describe alternatives you've considered**
- Setting up a reverse proxy which passes the bearer token.
- Switching to a different provider.

**Additional context**
Your user-facing dashboard still contains an absurd amount of third-party tracking functionality:  For a simple dashboard this is absolutely not appropriate and not in the users or customers interest. The dashboard  makes requests to Intercom, Sentry, Headway and Plausible.

**Comment by darkostanimirovic** [comment]
Hi @heipei, thanks for posting.

Let me break this down into individual points:

1. You want to replicate the Checkly public dashboard in your own UI.
    * Can you elaborate on the use case here? I assume this would allow your users to enter their Checkly dashboard URL and then your system pulls the data and displays in your own UI?
    * Is this mainly because of the tracking you mentioned or a better integration with your product?
3. You believe that we use an absurd amount of third-party integrations on the public dashboard, which isn't in the user's interest.
    * This is debatable. For example, Plausible is a very privacy-oriented alternative to Google Analytics. [See their privacy policy here](https://plausible.io/privacy). Sentry, while collecting more data, is only used to catch and pin-point bugs and improve user experience. We don't use Sentry data to build marketing cohorts or such.
    * I'll speak to the team about some of these other integrations, as they don't seem critical for the public page.
5. You want to access the check status API without authentication.
    * Why is the authentication an issue? Is it that you're trying to pull data for your customers without having to ask them for the token?

Thanks!

**Comment by heipei** [comment]
Hey @darkostanimirovic,

Let me answer your questions:

1. I want to replicate the Checkly public dashboard in my own UI, but only for my own service. I have a SaaS-service (urlscan.io) with a SPA app, and I want to pull in the metrics for my various checks into that service. I do not intend to pull in metrics for any other Checkly dashboards, hence it would be fine if this could be a per-account toggle (maybe even with "allowed origins").
2. Analytics: I believe that if I pay for a product I should have control over which third parties my and my customers data is shared with. Plus I don't see any benefit for me or my users on having an Intercom widget on the status page (what is that even for). Same for Plausible, why does this kind of tracking have to happen via third-party Javascript and not via inline / access logs analysis?
3. Authentication: I can reverse-proxy the API with my credentials, but it's just additional work for an API that used to work without authentication for me, so I'm asking whether it's possible to bring that back. What's the rationale for having auth in the first place for a public-facing read-only API?

I hope that makes sense, appreciate your fast response!

**Comment by heipei** [comment]
Also I just realised that proxying the API with a bearer token is not an option since this will also expose things like internal / private checks. So I don't have an effective way of displaying Checkly check information on my own website except the extremely basic SVG badges.

**Comment by nahuelon** [comment]
@heipei , here is Nahuel from Checkly. Have you seen our new [Public Dashboards](https://www.checklyhq.com/docs/dashboards-v2/)? You can read more about how are built in [this blog article](https://blog.checklyhq.com/announcing-incident-management-and-updated-dashboards/).
The new dashboards don't use Google Analytics, Sentry, Intercom nor Plausible.

**Comment by heipei** [comment]
@nahuelon Yes we're using the Public Dashboard and are very happy with the changes. It looks like the API works without authentication as well, this is great as it will allow us to pull in that data into our own app. Thank you so much!

**Comment by tnolet** [comment]
Closing this ticket!
