### ISSUE TITLE
Add the number of locations where a snippet is used to the main table displayed on /snippets

### ISSUE THREAD

**Issue by blinkfront** [checkly/public-roadmap#229]
**Is your feature request related to a problem? Please describe.**

I've recently been going through our code snippets and tidying them up - finding ones that were no longer in use or consolidating nearly-identical ones.

While doing this, I needed to easily find which snippets are not used in any tests or which are only used in a very small number of checks.

On the snippets screen I can do this by clicking on delete for a snippet and then it presents me with a list of where the snippet is currently used. However individually clicking through each snippet to find how many times it's used is quite a slow way to go about it when at some points we've had probably more than 50 snippets on our account (particularly as the page currently scrolls back to the top each time!)

**Describe the solution you'd like**

I can see there's an API endpoint used by your site which already exists at `/snippets/<snippetId>/checks` and which returns a list of the checks using a current snippet. 

Could the number of checks for a snippet be displayed on the main table of snippets as another column, alongside the snippet name and updated date? Perhaps alongside this, formatting could highlight snippets which are currently unused.

**Describe alternatives you've considered**

I had a quick look at the public API documentation and it seems that although `/snippets/<snippetId>` is available, `/snippets/<snippetID>/checks` isn't (and returns a 404 when requested).

**Comment by tnolet** [comment]
@blinkfront this is a good addition. Thanks

**Comment by tnolet** [comment]
@blinkfront this is now live! Thanks for contributing.

**Comment by blinkfront** [comment]
Amazing response time - thanks for adding it!
