### ISSUE TITLE
Private Dashboards

### ISSUE THREAD

**Issue by LyfegenJames** [checkly/public-roadmap#23]
As a Checkly administrator I would like to create private dashboards (View only TV mode style) and share them with third parties using individual username/password or other secure methods that ensure the dashboards are only viewable by authorised users.

These users should not count towards the "employee or user" count for billing but may be bundled as part of billing packages.

**Comment by tnolet** [comment]
Thank for reporting @LyfegenJames!

**Comment by SaudAlsaeed** [comment]
The feature is really important. We can at least have a private dashboard with the same login credentials. Just to give privacy to our APIs.

**Comment by tnolet** [comment]
@SaudAlsaeed thanks for adding this comment. We are prepping a set of new feature releases on this topic

**Comment by sergiotapia** [comment]
I would also like this, to have it on the TV.

**Comment by sts** [comment]
Authenticated dashboards would be great to see, as the urls can be easily guessed via publicly available information.

**Comment by suhas-chikkanna-liqid** [comment]
+1 From me as well.

I think this is quite a crucial feature for us ( and I believe to a lot of companies too). Absolutely, this information cannot be public and would be great, if there is an option to access these status dashboard via IP whitelisting. Please consider.

**Comment by Sam0711er** [comment]
We would also like to request that. ✌️

**Comment by tnolet** [comment]
@Sam0711er noted!

**Comment by chit786** [comment]
please can this be prioritized ? atleast having basic auth is also alright..

**Comment by sergiotapia** [comment]
Pretty crazy how it's been nearly three years and they still haven't added this simple feature.

**Comment by tnolet** [comment]
@sergiotapia @aslamkhan-atlan @chit786 thanks for upvoting this again. Two points:

- we prioritizes other concerns earlier than private dashes. This is painful but a fact of life.

- the upvotes and comments do not go unnoticed. You got the CTO responding 😅


Would love to know in each of your comments what type of auth would be an mvp for you that solves you and your team's problems.

**Comment by mwl** [comment]
> Would love to know in each of your comments what type of auth would be an mvp for you that solves you and your team's problems.

At Humio we had great success with URL authentication, so that anyone with the URL can see the contents of the dashboard. Especially in cases where we were managing digital signage monitors. Typing usernames, password, tokens or whatever is simply not an option when you manage 20+ Raspberry Pis showing various dashboards.

**Comment by tnolet** [comment]
Hi everyone, we are closing this issue in favour of https://github.com/checkly/public-roadmap/issues/243 as we are working on this right now. More news soon.
