### ISSUE TITLE
Add more intervals to the check run frequency

### ISSUE THREAD

**Issue by tnolet** [checkly/public-roadmap#235]
We are adding 2m, 2hrs, 3hrs, and 6hrs to the interval across all check types. This was a request in the below mentioned ticket

https://github.com/checkly/public-roadmap/issues/125

**Comment by case** [comment]
Thank you! Much appreciated.

**Comment by tnolet** [comment]
@case this is now live!

**Comment by case** [comment]
w00t, thanks!

I'm looking forward to your next Terraform Provider release. :)

> `Error: "frequency" must be one of [0 1 5 10 15 30 60 720 1440], got 360`

(from a `terraform plan` I just tried)

**Comment by tnolet** [comment]
@case this is coming up!

**Comment by tnolet** [comment]
@case this is live on our latest TF provider https://registry.terraform.io/providers/checkly/checkly/1.6.2
thanks @pilimartinez
