### ISSUE TITLE
Support for client certificates in API checks

### ISSUE THREAD

**Issue by janostgren** [checkly/public-roadmap#249]
The platform I am working use client certificates for authentication in all API.
We are interested of Checkly as the monitoring solution, but the support for certificates is required.
My client currently using Postman for ad hoc API, but like Checkly better. PM supports certificates so it can be used .

**Comment by darkostanimirovic** [comment]
Hi @janostgren and sorry about the delay.

Thanks for the feature request. We have some interest internally to build this soon but I can't give you any concrete ETAs. I'll update the ticket here once there is progress. If you have any additional feedback let me know.

**Comment by tnolet** [comment]
adding a reference here. Postman has an elegant solution https://learning.postman.com/docs/sending-requests/certificates/#managing-certificates

**Comment by tnolet** [comment]
@janostgren this feature is now live https://www.checklyhq.com/docs/api-checks/client-certificates/

**Comment by janostgren** [comment]
We intrersted of trying this solution with certificates in API checks, but
not force to use an Enterprise level license to evaluate it.
We want to start small with 5-10 checks !.

Den tors 10 nov. 2022 kl 16:52 skrev Tim Nolet ***@***.***>:

**Comment by tnolet** [comment]
@janostgren let me see if we can make that happen. Could you send me a short message via our support chat so I can have a look at your Checkly account?

**Comment by janostgren** [comment]
I an not the end customer. I am working for the customer as a consultant.
We can try it on my account. It is my email

fre 11 nov. 2022 kl. 10:41 skrev Tim Nolet ***@***.***>:

**Comment by tnolet** [comment]
@janostgren your email addresses are being redacted by GitHub issues so please contact us via the support and we'll get it going or mail me directly. First name at checklyhq.com
