### ISSUE TITLE
Pause Alerts for Maintenance Windows

### ISSUE THREAD

**Issue by OlllllllO** [checkly/public-roadmap#25]
**Is your feature request related to a problem? Please describe.**
At times we have the need to pause alerting for web/api tests. Sometimes it's a one time action other times it's a repeating action. We would like the ability to pause alerting on a per test basis for a given period of time.

**Describe the solution you'd like**
- Allow pausing alerts for a specific test
- Continue collecting data while alerting is paused (as it works now)
- Allow scheduling for a future date for a fix period of time
- Allow scheduling for a repeating date for a fixed period of time

**Describe alternatives you've considered**
- Manually pause the test - prone to forgetting/delaying enabling alerts
- Update via API and pause - heavy process for non-technical users that are aware of upcoming outage. 

**Additional context**
We use pager duty for alerts. If we need to stop alerts for all tests, PagerDuty allows maintenance window that is global. The scope of this request is on a per-test basis.

**Comment by tnolet** [comment]
@OlllllllO and other followers of this ticket: we have a beta release for this available very soon (i.e. this week-ish) and can enable this under a feature flag on your account. Just ping me here you are up for this.

**Comment by tnolet** [comment]
This feature is now released. Take it for a spin and let us now any bugs or issues.
