### ISSUE TITLE
Key-value tags

### ISSUE THREAD

**Issue by Coolomina** [checkly/public-roadmap#254]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
String tags are generally great for grouping and filtering data in a dashboard, but I feel they're kind of wasted if they're just strings, as they do not give me any context about what I'm filtering by. So for example, if I have the tag `payments` and I'm filtering by it I cannot answer any of these questions:

- Does this check belong to the "payments" team?
- Does this check belong to the "payments" service?
- Does this check belong to the "payments" business feature?
- What's "payments" anyway? 😅

I need to have a map in my head about what context the tag actually belongs to, and that can lead to misinformation eventually.

**Describe the solution you'd like**
I'm aware this can be a mess when trying to maintain retrocompatibility, but key-value tags really make the most out of having metadata in our cloud resources. They give us the context and the value of that context. 

**Describe alternatives you've considered**
Of course there's always the chance of having `team:payments` as a string tag, but I feel the indexing of that can be trickier and the filtering will probably be uglier.

Thank you!

**Comment by Coolomina** [comment]
Also, for propagating these tags to other providers, if they support key-value tags, you can just copy them. If they don't, you have the option of squashing that into `key:value` string tag.

I have seen #184 , so I assume this is a live feature. So what's the plan for propagating the current string tags to a provider that won't support them because they may use key-value?

**Comment by tnolet** [comment]
@Coolomina we probably are not revisiting this feature soon, so the `key:value` option is still the way to go for now.
