### ISSUE TITLE
Custom scheduling

### ISSUE THREAD

**Issue by rakesh-groww** [checkly/public-roadmap#257]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
I want to run api check only during a particular time of the day. I dont want checks to be running throughout the day.

**Describe the solution you'd like**
There should be an option to give crontab like scheduling. same syntax.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by tnolet** [comment]
@rakesh-groww thanks for mentioning this. Could you upvote this ticket? https://github.com/checkly/public-roadmap/issues/125
