### ISSUE TITLE
SLA decimal on dashboards

### ISSUE THREAD

**Issue by szimbaro** [checkly/public-roadmap#262]
Hello, is it possible having two decimal after the comma on dashboard? As we have in home of the administrative console ?

app.checklyhq.com home:
![image](https://user-images.githubusercontent.com/1026313/194899563-fad78bf8-c35e-43fa-a097-4960d2235ea7.png)

Dashboard status page:
![image](https://user-images.githubusercontent.com/1026313/194899515-e824ee08-b7da-4e65-956d-ccf7a93e8528.png)

**Comment by tnolet** [comment]
@szimbaro hmm, this seems like a small regression. We are working on a whole new dashboard which does "five nines" i.e. 99.934%, but we should fix this in between. Thanks for mentioning

**Comment by nahuelon** [comment]
@szimbaro , the dashboard shows three decimals ("five nines") percentages now. Thanks for notice and share it.

![image](https://user-images.githubusercontent.com/5315705/195344704-6f45203c-0a20-4dd2-94af-0a08bc19b77a.png)

**Comment by szimbaro** [comment]
Thanks for the quick response.

---
Saulo Zimbaro
+55 21 99800-0100
