### ISSUE TITLE
Add GROUP_BASE_URL as an environment variable for use in setup/teardown scripts

### ISSUE THREAD

**Issue by rdelcampog** [checkly/public-roadmap#263]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
Would be great that the `{{GROUP_BASE_URL}}` variable can be used in a Setup script by using "process.env.GROUP_BASE_URL" as for now, this variable can only be used in the URL field.

If you run a `console.log(process.env)` inside a setup script, you'll see that there is no `GROUP_BASE_URL` variable defined.

**Comment by tnolet** [comment]
@rdelcampog great idea. That variable started out as an "internal" thing but I see no reason why you should be able to have access to it.

**Comment by tnolet** [comment]
@ianaya89 should be a quick fix

**Comment by zdumitru** [comment]
Would be great to have the variable available.

**Comment by tnolet** [comment]
@ianaya89 could we add this?

**Comment by ianaya89** [comment]
@nahuelon was taking care of this, I will catch up and get back.

**Comment by nahuelon** [comment]
@ianaya89 @tnolet , https://github.com/checkly/checkly-backend/pull/3659 is ready for review.

**Comment by nahuelon** [comment]
@rdelcampog , good morning. We just added two new environment variables: `GROUP_BASE_URL` and `REQUEST_URL`. You'll find them in our [docs](https://www.checklyhq.com/docs/api-checks/setup-teardown-scripts/#general-runtime-variables). Thanks for your feature request.
