### ISSUE TITLE
Home dashboard enhancements

### ISSUE THREAD

**Issue by tnolet** [checkly/public-roadmap#268]
The Home Dashboard is the most used page in the Checkly web app. We want to optimize various aspects of the experience:

1. Sorting failing checks to the top.
2. Sorting and filtering enhancements to quicker discover relevant data for users with a lot of checks and groups.
3. Better feedback on running adhoc checks directly from the dash.
4. Responsive layout for users on the go.

**Comment by artembondadefiyeld** [comment]
Guys, do you have plans to make public dashboards a bit more customizable in terms of metrics to show to users? For example, in our case, we would like not to show P95 and P95, just only basic numbers like availability %.

**Comment by tnolet** [comment]
@artembondadefiyeld thanks for contributing, but this ticket is for the Home dashboard in the app itself, so not the public dashboards. But we have had that feedback and will look at it.

**Comment by tnolet** [comment]
This ticket is now done!

- Failing checks are now show in the Firewatch widget!
- Failing checks can be rerun from Firewatch in bulk.
- Layout is fully responsive.
