### ISSUE TITLE
Dead man's switch

### ISSUE THREAD

**Issue by homtec** [checkly/public-roadmap#269]
Hey Checkly team,

**Is your feature request related to a problem? Please describe.**
We want to monitor a software component that is not accessible via external REST interfaces. We need to make sure this component is working properly. 

**Describe the solution you'd like**
It would be great to have a "Dead man's switch". Our system pings a checkly endpoint and if it doesn't do for some time, an alert is triggered. 

Thank you ✌️

**Comment by tnolet** [comment]
Hey @homtec thanks! Could you upvote this issue? https://github.com/checkly/public-roadmap/issues/72
