### ISSUE TITLE
Simplify creation of new teams

### ISSUE THREAD

**Issue by pluspol** [checkly/public-roadmap#274]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
As an agency which works for multiple clients it happens that we create Checkly teams for our clients and are also part of multiple teams.
Currently when creating a team for our client we have to use a different email address each time.

**Describe the solution you'd like**
When logged in there is an option to create a new team and become its owner.

**Comment by tnolet** [comment]
@pluspol yes, this is coming ASAP. The solution we have in early draft would enable the following:
- one main account with billing details etc.
- multiple sub-accounts that are logically separated, essentially the same as signing up for another account. This sub-account can be used for a new team, new customer project, new service: essentially whatever use case you see fit for a separated account, while still accessible from one set of credentials.

Let me know if we are missing any use case here.

**Comment by pluspol** [comment]
Thanks @tnolet for the details.
This looks good to me. The only thing I'm not sure I've understood correctly:
Would passing the ownership of a team also change how billing works?
In our usecase we might create a team for our client and after setting it up transfer the ownership to the client. The client then also would enter the billing details. We would still be part of the team - as admin.

**Comment by tnolet** [comment]
@pluspol I understand, that is indeed a bit of a different use case. You effectively do not want a "main" account that takes care of billing. You want an option to split off that account from the main account and let it have its own billing. 

Staying admin is always possible, like it is right now. Just need to be invited to an account with the Admin role.

**Comment by pluspol** [comment]
That's right @tnolet. For us both use cases may be relevant (multiple teams on our billing account and creating a team with a separate billing account).

Maybe something like this is feasible:
I'm assuming billing is linked to the ownership of a team.
In this case two things would be possible:
- At first you just create a new team from your account. Because the ownership stays with the main account the billing details do too.
- Secondly it's possible to transfer the team ownership to another account. This also changes the billing details as billing is linked to the ownership.

**Comment by tnolet** [comment]
@darkostanimirovic this seems like something you should have a look at

**Comment by darkostanimirovic** [comment]
Hi @pluspol. Last week we shipped an early iteration for team management and it should satisfy your use case.

In the accounts dropdown, there's a new link to Create a Team. This effectively creates a new account where you are the owner. You can then stay as an admin while transferring the ownership to the client so they can manage billing and the account.

In future we will likely give you more control of the process and further options for those who need to manage billing in one place. If you have any feedback please either respond here or ping us at support@checklyhq.com.

**Comment by pluspol** [comment]
Hi @darkostanimirovic,
Thanks for the feature. It sounds great!

I can confirm seeing the dropdown link.
I'm currently member of two teams. However the link is only active when I've switched to the team I'm the owner of (it's on the FREE plan). In the other one where I'm only admin (it's on the PREMIUM plan), the link is disabled.
Is this correct? IMHO creating teams shouldn't have any relation to other teams.
