### ISSUE TITLE
Allow checks without Schedule

### ISSUE THREAD

**Issue by zomars** [checkly/public-roadmap#275]
**Is your feature request related to a problem? Please describe.**
I want to disable check frequency. 

**Describe the solution you'd like**
I need some check to just run on a production deploy from Vercel.

**Describe alternatives you've considered**
Setting it to 24 hours but that's not the optimal solution since the intention is to run these checks ONLY when deploying to production.

**Additional context**

**Comment by tnolet** [comment]
@zomars thanks for reporting. We got this on our radar. I'm linking it to this overarching request https://github.com/checkly/public-roadmap/issues/125

**Comment by tnolet** [comment]
To give some context: this is a longer standing request and I / we 100% see the need for it. More and more of our customers are mostly getting value out of Checkly by triggering the checks on deploy. We are adjusting some parts of our infra but also our plans & pricing to start enabling this. More news ASAP.

**Comment by tnolet** [comment]
@zomars would love to know if this solution works for you.

**Comment by tnolet** [comment]
@zomars and other. We have a clean split between monitoring and testing now. Please see our updated docs on how to achieve this. https://www.checklyhq.com/docs/testing/
