### ISSUE TITLE
Wrong incident update date in overview page

### ISSUE THREAD

**Issue by mbernasocchi** [checkly/public-roadmap#284]
**Is your feature request related to a problem? Please describe.**
when an incident goes over two days, the date shown on the main status page is the one of the first reports with the text of the last update, which is very confusing

**Describe the solution you'd like**
ideally, the date shown would be the date of the last update since that is the visible text.

![image](https://user-images.githubusercontent.com/233663/215231842-ebe2d248-0c27-45dc-aa61-c446139f168d.png)
![image](https://user-images.githubusercontent.com/233663/215232140-2490ef46-b303-4e58-875b-6b7cfd39244f.png)

**Comment by tnolet** [comment]
@mbernasocchi we have a fix for this in PR stage. Should be live soon

**Comment by tnolet** [comment]
@mbernasocchi and other, this fix is live right now. Thanks for reporting!
