### ISSUE TITLE
FireHydrant Integration for TF Provider

### ISSUE THREAD

**Issue by gespi-consensys** [checkly/public-roadmap#296]
**Is your feature request related to a problem? Please describe.**
We use FireHydrant to manage our incidents and noticed that Checkly supports Firehydrant integration on the UI but not on its Terraform provider. Please add the same integration for the TF provider

**Describe the solution you'd like**
A way to integrate our TF checkly config with Firehydrant integration on Checkly.

**Comment by ianaya89** [comment]
@gespi-consensys thanks for your request. We will have this working soon.

**Comment by ianaya89** [comment]
@gespi-consensys I just released a new TF provider version, including support for `FireHydrant` and other integrations. 
Here an example of how to create one:

```tf
# A Firehydran alert channel integration
resource "checkly_alert_channel" "firehydrant_ac" {
  webhook {
    name         = "firehydrant"
    method       = "post"
    template     = <<EOT
{
  "event": "{{ALERT_TITLE}}",
  "link": "{{RESULT_LINK}}",
  "check_id": "{{CHECK_ID}}",
  "check_type": "{{CHECK_TYPE}}",
  "alert_type": "{{ALERT_TYPE}}",
  "started_at": "{{STARTED_AT}}",
  "check_result_id": "{{CHECK_RESULT_ID}}"
},
    EOT
    url          = "https://app.firehydrant.io/integrations/alerting/webhooks/2/checkly"
    webhook_type = "WEBHOOK_FIREHYDRANT"
  }
}
```

Let me know how it works and if you have further questions.

Thanks!
