### ISSUE TITLE
Allow perf metrics to be disabled on dashboard/status page

### ISSUE THREAD

**Issue by leite08** [checkly/public-roadmap#303]
**Is your feature request related to a problem? Please describe.**
Currently, there's no way to disable performance metrics from being displayed on public dashboards (status page).

**Describe the solution you'd like**
Include a checkbox on the dashboard's edit page to disable displaying performance metrics.

**Describe alternatives you've considered**
Considered using CSS to hide performance metrics, but this has a few problems:
1. It only hides them, but they're still available on the HTML;
2. It also hides the availability/uptime percentage, as it shares the CSS class with the P metrics;
3. The width of the graphs doesn't increase/adjust, so we end up with a white space where metrics were being displayed;
4. Should the CSS class change, the work around will not work anymore.

**Additional context**
Without that toggle we won't be able to use the public dashboard and will need to consider other solution for this, which decreases the value we get from using Checkly.

**Comment by tnolet** [comment]
@leite08 thanks for reporting. Keeping track of this for next iteration

**Comment by ianaya89** [comment]
Hi @leite08, we just shipped new settings to the public dashboard. You should be able now to toggle `p99` and `p95` metrics.
We have yet to implement any design changes when the metrics are hidden, but we will start working on that soon.

**Comment by leite08** [comment]
Nice! Thanks for letting us know @ianaya89!

**Comment by ianaya89** [comment]
Hey @leite08, we just updated the design and results will expand if you have less metrics :)

**Comment by leite08** [comment]
Cool, thank you!
