### ISSUE TITLE
GeneralAssertionBuilder's notContains method calls AssertionComparison.CONTAINS inside

### ISSUE THREAD

**Issue by MikulasMascautanu** [checkly/public-roadmap#306]
**Is your feature request related to a problem? Please describe.**
The `notContains` method of `GeneralAssertionBuilder` calls `CONTAINS` `AssertionComparison` inside. [Here is a permalink to the line of code](https://github.com/checkly/checkly-cli/blob/06a64b2767d0ac792c8268d08c1ea012a1f01039/packages/cli/src/constructs/api-check.ts#L151).

This results, for example, in this unexpected behavior:
- I call `AssertionBuilder.textBody().contains('avatar')` and `AssertionBuilder.textBody().notContains('avatar')`
**Expected behavior**: I see both of these assertion results when I run the check.
**Actual behavior**: I see only the first assertion (as they are merged into one, I think).
Here is a screenshot, I've also added one more assertion after the mentioned two so you can see it really skips the middle one:
![image](https://user-images.githubusercontent.com/68233869/236491514-ce7dc063-6931-4dca-92cf-67cc78fce727.png)
And here is what the same code results into when I change the culprit line in `@checkly/cli` to the proposed one:
![image](https://user-images.githubusercontent.com/68233869/236491981-37bf54a7-63b2-42ee-b8ce-bc61e729c317.png)

**Describe the solution you'd like**
The `notContains` method should call `NOT_CONTAINS` `AssertionComparison` inside it, as follows:
```
    notContains(target) {
        return this._toAssertion(AssertionComparison.NOT_CONTAINS, target);
    }
```

**Comment by clample** [comment]
@MikulasMascautanu thank you again for tracking down this bug and fixing it! Your PR is now released in [checkly@4.0.5](https://www.npmjs.com/package/checkly/v/4.0.5). Just a heads up, we recently moved the NPM package from `@checkly/cli` to `checkly`.
