### ISSUE TITLE
Configurable time period columns in dashboards

### ISSUE THREAD

**Issue by yannislionis** [checkly/public-roadmap#307]
I was disappointed when I created a dashboard with some API checks and the dashboard showed last 24H and last 7D, but there was no way to configure those. I was looking to configure it to 30D. I know the data is available for this an I can access it in Reports. However it would be awesome to be able to share Dashboards with our customers that I can customise according to our Uptime and SLA agreements. So:

**As a** Checkly User creating a Dashboard
**I want** to be able to configure custom durations in the Dashboard columns
**So that** I can get an easy view of the time periods that are important me and gush to my friends about how awesome Checkly is

**Comment by ianaya89** [comment]
Hi @yannislionis, thank you for sharing your feedback. As of now, we do not support custom periods, but with the new dashboards, you can access statistics for 24-hour, 7-day, and 30-day periods by default.

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/3258966/236522544-fb76a938-0f84-4278-990f-879b55e5c1c0.png">

In addition to the existing timeframes, do you have any specific periods in mind, or are you looking for full control over this feature? We appreciate your input and will take your request into consideration for future updates.

**Comment by yannislionis** [comment]
Hm, that's now what I see! Screenshot below. But you mentioned "the new dashboards" is this a new feature I don't have access to yet? 
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/70198/236524241-a374786b-2949-4b84-bbfa-6d88e94fc62d.png">

**Comment by ianaya89** [comment]
@yannislionis  We released the new dashboards a few months ago (under a new domain, `checkly-dashboards.com`) we a bunch of new improvements and incidents management.
You should be able to access it using your custom URL `https://your-custom-url.checkly-dashboards.com`, or pointing your custom domain to `checkly-dashboards.com`

[Here](https://www.checklyhq.com/docs/dashboards/legacy-dashboards/#migrating-to-dashboards-v2) you have a migration guide. If you need further assistance, feel free to join our [slack community](https://www.checklyhq.com/slack/) and will be able to help you there.

**Comment by yannislionis** [comment]
Brilliant, and apologies I didn't know about this! Thank you!
