### ISSUE TITLE
Support for running inside TypeScript + ESM packages

### ISSUE THREAD

**Issue by alvarlagerlof** [checkly/public-roadmap#310]
**Is your feature request related to a problem? Please describe.**
I want to convert the package in an internal monorepo containing a NextJS site into a ESM module, with `"type": "module"`. This works, except for the Checkly CLI that does not support it.

**Describe the solution you'd like**
Support for running in TypeScript + ESM packages for the Checkly Cli.

**Describe alternatives you've considered**
Moving all of our Checkly code to another package in the monorepo. This is not ideal from a code-reuse perspective because having it in the same repo as the site allows some imports that don't make sense to extract to other packages.

**Comment by tnolet** [comment]
@alvarlagerlof closing this in favour of https://github.com/checkly/checkly-cli/issues/619
