### ISSUE TITLE
Add success ratios to the API 

### ISSUE THREAD

**Issue by dalehumby** [checkly/public-roadmap#32]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to get the latest results of all checks, including the success ratios in one API call

**Describe the solution you'd like**
In the /v1/checks I would like to have 
- latest pass/fail status of the check
- average response time
- success ratios for 1 day, 7 days and 30 days
for each of the checks

**Describe alternatives you've considered**
- In the API: for each check, iterate over all the results for the last 30 days calculate the success ratio from that data. But the API offset, limit, paging makes it too difficult.
- The web dashboard doesn't display 30d success ratio unless you click on each request
- The prometheus integration doesn't surface success ratios either

**Additional context**
I'd like a single place where I can see whether checks are passing/failing, and how much of my error budget I have used for the last 1 day, 7 days, 30 days for operational and reporting purposes.

**Comment by tnolet** [comment]
@dalehumby Moving this to our Q4 goals. This is a very very old ticket but we are going to deliver it in a slight different way than you requested. We will expose a generic reporting API from which you can pull availability and other metrics in any format you would like across any time range.

**Comment by tnolet** [comment]
https://github.com/checkly/public-roadmap/issues/233

**Comment by tnolet** [comment]
This is now live under the new `/v1/analytics` endpoint. The metrics are requestable per check type and per check.

- https://developers.checklyhq.com/reference/getv1analyticsapichecksid
- https://www.checklyhq.com/docs/analytics/
