### ISSUE TITLE
Allow setting the favicon and title on dashboard

### ISSUE THREAD

**Issue by tnolet** [checkly/public-roadmap#37]
Customer request for:
- specifying the favicon
- specifying the HTML head title element

![image](https://user-images.githubusercontent.com/3802923/62124980-faf55c80-b2cb-11e9-98bc-861ef3296710.png)

**Comment by scottlinlin** [comment]
I need it ,please add it as soon as possible!

**Comment by tnolet** [comment]
done https://www.checklyhq.com/docs/dashboards-v2/dashboard-customization/
