### ISSUE TITLE
Add support for p99 latency to dashboards

### ISSUE THREAD

**Issue by ryanchapman** [checkly/public-roadmap#39]
**Is your feature request related to a problem? Please describe.**

I would like a way to display p99 latency on the dashboard.  Right now we can see AVG latency, but in our world, AVG might be like saying "we only care about the experience of a subset of our users."  For example, one of our key services has a p50 latency of 10ms, p95 of 60ms and p99 latency of 200ms (numbers taken from Stackdriver, not Checkly).

**Describe the solution you'd like**

There are several options.
1) Add a p99 column to the dashboard
2) Allow for custom dashboards that let the user select the fields displayed.  This might be desirable for public dashboards where you might not want to show p99 latency, but AVG would be better (maybe for marketing reasons).
3) ?? maybe a better solution

**Describe alternatives you've considered**

I see p99 in alerts, so I assume the data is being captured.  I don't see any options for adding p99 in dashboard configuration.

**Additional context**

**Comment by tnolet** [comment]
Hey @ryanchapman thanks for submitting. I'm aware of this need and I've cross linked this issue with https://github.com/checkly/product-roadmap/issues/17

**Comment by tnolet** [comment]
@ryanchapman we just added the p95 value to the home dashboard, but not the public dashboards yet. Hope this is already a step in the right direction. The public dashboards are going into another sprint for an update.

**Comment by ryanchapman** [comment]
@tnolet Thanks for the update.  Did you mean p99?

**Comment by tnolet** [comment]
@ryanchapman we added p95 for now as it tends to give a more balanced view. If this works out database load wise, we will proceed to add p99 in the future.

**Comment by tnolet** [comment]
closing! https://www.checklyhq.com/docs/dashboards-v2/

**Comment by ryanchapman** [comment]
Thanks Tim!
