### ISSUE TITLE
Enable a way to tag alerts so they are enabled only for certain products

### ISSUE THREAD

**Issue by Nicki-Susman** [checkly/public-roadmap#52]
For example, we have a channel for Product1 alerts, only our tests tagged with "Product1" should generate those alerts. It would be great if instead of doing an all or nothing approach and manually assigning these specific ones, we could tag the alert, and any tests with that alert would be subscribed unless manually unsubscribed.

**Comment by tnolet** [comment]
A parallel solution for this problem will probably be our upcoming grouping feature 

https://github.com/checkly/product-roadmap/issues/13

Groups allow you to create alert channels per group. Groups can be per product, team, service etc.

**Comment by tnolet** [comment]
this ticket is closed as it is solved by groups
