### ISSUE TITLE
Collective Monthly reporting 

### ISSUE THREAD

**Issue by aliasgerkw** [checkly/public-roadmap#59]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
There is no place in the system where I can collate all historical data and dump it to some google sheets for analysis.

**Describe the solution you'd like**
Along with weekly "Your Checkly 7-day performance summary" email we should have an integration with Google sheets were I can push the data containing Uptime percentage, p95 response time etc which can we shared with team for analysis and performance tuning. 

**Describe alternatives you've considered**
Export button in Dashboard to see past data atleast

**Additional context**
This should be very crucial for team trying to achieve 100% uptime and reducing customer downtime.

**Comment by tnolet** [comment]
@aliasgerkw thanks for adding this! Reporting and data export are on the roadmap for this year. Current customers are using either the Prometheus integration or our API to export data, but a "download as CSV" is high on our list.

For you reference, see our check-results and rolled up check-results API endpoints.

https://checklyhq.com/docs/api/#checkly-api-check-results

**Comment by aliasgerkw** [comment]
Prometheus integration means Slack, Webhook etc right? 
Also If I use API what is time frame for which I will get data from the system? Are you storing everything?

**Comment by aliasgerkw** [comment]
@tnolet I was check Check results API that schema does not contains parameter to read success ratio and other items which I got in the summary email. Am I missing something?

**Comment by tnolet** [comment]
> Prometheus integration means Slack, Webhook etc right?

No, it means the Prometheus integration explained here https://checklyhq.com/docs/integrations/prometheus/

> Also If I use API what is time frame for which I will get data from the system? Are you storing everything?

We store all details for 30 days, then we roll up the data as explained here:
https://checklyhq.com/docs/monitoring/how-we-store-data/

**Comment by tnolet** [comment]
> @tnolet I was check Check results API that schema does not contains parameter to read success ratio and other items which I got in the summary email. Am I missing something?

This is correct. The ratio are calculated on the fly by our backend as you request them. The API gives you access to the raw request data so you can do aggregates yourself.

**Comment by tnolet** [comment]
@aliasgerkw this one should be tackled by the reporting page https://app.checklyhq.com/reporting
You can grab a CSV export or use the reporting API at https://www.checklyhq.com/docs/api#operation/getV1Reporting
