### ISSUE TITLE
Need options/controls for SSL expiration checks and alerting

### ISSUE THREAD

**Issue by zswanson** [checkly/public-roadmap#61]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
I recently tied Checkly to OpsGenie alert webhooks. All of our APIs tested by Checkly are under a single ssl cert and (sub)domain name. When we hit the 30 day expiration point Checkly fired that as an alert for all of our tests, bombarding me with OpsGenie alarms in the wee hours of the morning. I didn't realize that the SSL alert would actually go out over the OpsGenie webhook, but there's also no way for me to turn it off, limit it to a single alert, etc.

**Describe the solution you'd like**
I would suggest these options:
* A way to toggle an SSL alert on/off per alert
* A way to toggle whether SSL alerts should go out over a particular notification channel
* Backend handling on Checkly so that if 15 endpoints being tested all have the same cert, you only send one alert.

**Comment by tnolet** [comment]
@zswanson noted we will probably go for a combination of point 2 and point 3

**Comment by tnolet** [comment]
@zswanson this is in progress!

**Comment by batuhan** [comment]
@zswanson this is live! find the details on our announcement post: https://blog.checklyhq.com/improving-the-ssl-certificate-expiration-alerts/

**Comment by zswanson** [comment]
Love it! You guys are great
