### ISSUE TITLE
Dashboard Status Events

### ISSUE THREAD

**Issue by jdmcd** [checkly/public-roadmap#63]
**Is your feature request related to a problem? Please describe.**
Right now I have to use two different services for users - Checkly for monitoring uptime, etc, and a different status page provider for their maintenance notice features. 

**Describe the solution you'd like**
I would love to see the ability to add maintenance notices, status alerts, and postmortems to the public dashboard for people to subscribe to. I would 100% rather pay Checkly more to do all of it rather than splitting features across two services. 

**Describe alternatives you've considered**
Sticking with Checkly for monitoring and Freshstatus for status pages

**Comment by tnolet** [comment]
@mcdappdev great suggestion and we are working on a solution for this, pretty much like you describe it.

**Comment by mcdappdev** [comment]
Awesome! Looking forward to it :)

**Comment by daolf** [comment]
I was wondering if you had any news on this? 

We are also looking to have both uptime monitoring and status reporting on one single page, and it seems like a few solutions there do both very well.

**Comment by tnolet** [comment]
@daolf thanks for enquiring. This feature is still on the list, but we had to de-prioritize it a bit. We have shipped the maintenance windows part, but this is not yet visible on the dashboard / status pages. 

As you mention, there are quite some solutions already out there so it is a bit harder for us to distinguish ourselves in this market. Having said that, I think for devs, small businesses and solo-projects it makes total sense to have it all in one package. I hope we can deliver this in Q1 next year.

**Comment by tnolet** [comment]
@daolf forgot, please give the tracking issue https://github.com/checkly/public-roadmap/issues/65 a 👍 so we can track interest. tnx

**Comment by daolf** [comment]
Done, thanks  ✅

**Comment by daolf** [comment]
Hi Tim.

Any news about this status reporting feature?

Regards

Pierre

**Comment by tnolet** [comment]
@daolf sorry no hard update on this yet.

**Comment by tnolet** [comment]
@daolf @jdmcd this feature was shipped a while ago, but forgot to update this ticket. Please see the Incidents feature on our Dashboards V2 https://www.checklyhq.com/docs/dashboards-v2/incidents/
