### ISSUE TITLE
Status page V1

### ISSUE THREAD

**Issue by tnolet** [checkly/public-roadmap#65]
# Problem Statement
"As an engineer I want to share the status of my app /  service with my customer and internal stakeholders."

# Proposed Work

The current "dashboards" feature will be deprecated

## Management:

- [x] CRUD for incidents
- [x] promote incidents through stages: initial, investigating, solved.
- [x] add / remove updates to incidents
- [x] add remove checks and check groups
- [x] incidents with configurable categories: outage, maintenance etc.
- [x] show scheduled maintenance

## Look & feel:

- [x] set title
- [x] set user configurable description
- [x] set title HTML tag
- [x] set favicon
- [x] upload logo image
- [x] logo is clickable and has a configurable URL
- [x] Mobile first

## Performance
- [x] possibly server side render
- [x] reduce dependencies
- [x] remove unneeded 3rd party includes (Google, Intercom, etc.)

Stretch goals for V1, otherwise V2.

Subscribing:

- allow email signup
- verify email
- unsubscribe
- admin management
- add / edit / remove emails

Private dashboards

- User management / CRUD on users
- Reset password
- Some basic "last logged in" analytics

**Comment by tnolet** [comment]
#17
#35
#36
#37 
#39 
#63

**Comment by heipei** [comment]
Just wanted to underline that I currently have two things that bug me about the dashboards:

- No HTTP/2 with custom CNAME due to the Express proxying, makes this unusable and forces me to proxy the custom domain myself which kinda defeats the purpose.
- No responsive status page, hard to use on mobile, hard to put in an iframe.
- Status page feels "too heavy" wrt to how many requests are made in the background for something so simple.

Looking forward to the next iteration!

**Comment by tnolet** [comment]
@heipei thanks for mentioning this. Noted and will be taken into account!

**Comment by franciscolourenco** [comment]
The current status pages / dashboards look pretty nice. At the moment just missing the ability to change the order in which the checks appear. Thanks!

**Comment by tnolet** [comment]
> The current status pages / dashboards look pretty nice. At the moment just missing the ability to change the order in which the checks appear. Thanks!

Noted! Thanx

**Comment by abenhamdine** [comment]
Sounds exciting !
Is it planned to allow to customize status page theme ?
For example by defining some css ?

**Comment by tnolet** [comment]
@abenhamdine yes, no, maybe! We are tracking this here. So consider your request noted!

**Comment by tnolet** [comment]
https://github.com/checkly/public-roadmap/issues/140

**Comment by philipp-tailor** [comment]
+1 for this issue! Recently had an incident not covered by Checkly checks, and thus our public status page claimed that all systems were a 100% operational, which was incorrect.
The most MVP solution for me would be to add a free text area. Then I could have described the ongoing incident, it would have appeared on our status page. After it was resolved I could have cleared the text area.

**Comment by rlevy-byway** [comment]
Private dashboards with login would be great. Even if it is a single shared login. I.e. so internal business team can see status reports behind a login.

**Comment by mbernasocchi** [comment]
do you have any timeline on this? we really would love to be able to show maintenance windows on the status page.
incident reports would also be great but least important. Maybe you could simply allow adding a link at the bottom of the dashboard?

**Comment by abenhamdine** [comment]
Incidents on the status page is a must-have 🙏 
I can promise you that if you ship that feature, you will steal tons of clients which currently use the costly Atlassian status page 😃

**Comment by tnolet** [comment]
@abenhamdine thanks for chiming in here. First the bad news: at this point, I'm not 100% decided on adding full incident management to Checkly. It will distract from our core proposition, which is running checks REALLY well.

However (the good news) we will start work on upgrading our current dashboards this quarter and I think a way of adding custom messages to the dash is 100% in scope. Also @heipei has made some great comments on purely technical downsides for instance. Expect some action on this is in the coming period.

**Comment by tnolet** [comment]
To all following this ticket: I have more tickets for you to follow! 😅 We are splitting the work on our public dashboards / status pages into separate initiatives. First two tickets are up, covering the first technical and functional improvements. They cover the work we will do at a high level of course, so eventual product might be slightly different.

https://github.com/checkly/public-roadmap/issues/237
https://github.com/checkly/public-roadmap/issues/238

**Comment by peter-dolkens** [comment]
Another suggestion for dashboards: Let us either expose the group, or filter which tags to hide/show

I have a "client-<clientname>" tag on all my tests, and they're organized into client specific groups, but right now a check for all "environment-production" checks looks like this...

![image](https://user-images.githubusercontent.com/469666/188466559-7b22d7d0-31ee-4d3c-bb47-c3d614ace32f.png)

**Comment by tnolet** [comment]
Hi all, we will communicate broader very soon, but we have some great upgrades to our dashboards in preview right now. Just wanted to let everyone know as early as possible 😀  We did not get to ship all the need-to-haves and nice-to-haves in this release, but we didn't want to wait any longer. Here is the gist:


- Enable the new dashboards (with incident management) in our new Labs section at https://app.checklyhq.com/settings/account/labs

- Try out the new dashboard, with a brand new design, more data over longer time ranges. 

- The new dashboards are now hosted under `checkly-dashboards.com`. This means you will have to update you DNS if you're using a custom domain.

- Try out the incident management, docs here https://www.checklyhq.com/docs/dashboards-v2/incidents/

- new docs are live here [https://www.checklyhq.com/docs/dashboards-v2/](https://www.checklyhq.com/docs/dashboards-v2/)


P.S. we are heavily shipping last tweaks, performance improvements etc. as we speak and would love to get early feedback.

**Comment by abenhamdine** [comment]
Such great news ! Thx @tnolet for the preview feature 👍

**Comment by tnolet** [comment]
@heipei we are adding this manually right now (ship early!). Just added your domain. Should be good!

**Comment by tnolet** [comment]
We are using Vercel now for all hosting & SSL duties. This should also help drastically with good load times via their CDN, whereas we first had a Caddy setup in the eu-west-1 region on AWS.

**Comment by abenhamdine** [comment]
The new v2 dashboard is great, we use it for one week now 👍

**Comment by tnolet** [comment]
This ticket is now closed! We did not add the Subscribing and Private dashboards due to time and scope constraints.
New docs are here https://www.checklyhq.com/docs/dashboards-v2/
