### ISSUE TITLE
Playwright integration

### ISSUE THREAD

**Issue by tnolet** [checkly/public-roadmap#67]
# Problem Statement
"As an engineer, I want to use Playwright as an alternative to Puppeteer for testing an monitoring my web apps and web sites"

# Proposed Work
- Integrate Playwright in our backend runners
- Initially support Chrome, investigate Edge and Firefox.
- Allow user to specify either Puppeteer or Playwright
- Provide same experience in writing checks and collecting results and alerting
- Provider examples and guides on writing effective Playwright checks

**Comment by batuhan** [comment]
We've just announced our Playwright support on our blog: https://blog.checklyhq.com/we-now-support-playwright/

Also, we've added Playwright support to our Recorder project! https://github.com/checkly/headless-recorder
