### ISSUE TITLE
Support client-side certification authentication

### ISSUE THREAD

**Issue by clavoie-renorun** [checkly/public-roadmap#71]
**Is your feature request related to a problem? Please describe.**
Cannot monitor bits of websites behind client-side certification authentication.

**Describe the solution you'd like**
Have checkly support client-side certificate.

**Comment by tnolet** [comment]
@clavoie-renorun thanks for contributing! We will take not of this.

**Comment by tnolet** [comment]
@clavoie-renorun and others. We support client certificates right now https://www.checklyhq.com/docs/api-checks/client-certificates/
