### ISSUE TITLE
FR: schedule checks for business hours only

### ISSUE THREAD

**Issue by wvanderdeijl** [checkly/public-roadmap#74]
**Describe the solution you'd like**
Would be nice if we can schedule checks to only run during certain hours or days. We monitor an API that spins up a fairly expensive serverless container (Google App Engine). The application itself is normally only used during business hours, so we would be fine with only monitoring from 08:00 to 20:00 on weekdays. This would mean we only run 5x12 = 60 hours of AppEngine per week instead of 7x24 = 168 hours of AppEngine per week, which is a savings of 65%.

**Describe alternatives you've considered**
We' considered to alter the request URL in the setup script to a known good URL when the test runs outside of business hours. But that would also mean a failing API would be red during the day and suddenly switch to green at night since we manipulate the URL to some other address.

**Comment by tnolet** [comment]
@wvanderdeijl It might be a TOTAL coincidence but we *just* shipped our maintenance windows feature. It should be enabled in your account right now. You can use that feature to effectively "unschedule" checks for certain periods. In your case, it's not really maintenance, but the outcome is the same.

**Comment by wvanderdeijl** [comment]
Ah, that's great. I had seen the maintenance window feature but expected it to just not complain about failed checks, so basically a scheduled mute. But it seems a maintenance window actually disables the checks during the window. That's exactly what we are looking for.

**Comment by hitk6** [comment]
We have a similar requirement to schedule checks on working days.
start checks at : 9 0 * * MON-FRI
stop checks at : 21 0 * * MON-FRI

How can we achieve this in checkly ?

**Comment by tnolet** [comment]
@hitk6 thank for responding. Maintenance windows are a bit different. You are mentioning scheduling checks using cron statements. That is a very cool feature, but strictly not related to cron based schedules. Right now, we do not support this. You could use our API to enabled/disable checks on your own cron schedule

**Comment by hitk6** [comment]
I can create cron jobs for now to schedule checks, but maintaining 2 cronjobs (start, stop) for each domain is a hassle.

It would be great if the schedule checks feature is made available inbuilt in checkly in future versions. As we have lots of domains where we want to use schedule checks.
