### ISSUE TITLE
Custom date for SSL certificate expiration alert

### ISSUE THREAD

**Issue by Haubersch** [checkly/public-roadmap#76]
Problem of Checkly customer: Their SSL certificate provider only allows to renew certificate 30 days before it expires. In the Checkly settings there is the option of a 30 day check, which they prefer to use. Unfortunately they always get an SSL warning on this very day. Option for a 29 day warning would be nice.

**Comment by umutuzgur** [comment]
This is now live! You can select now from 1-30 days in your alerts
