### ISSUE TITLE
Adding tags to Slack notification

### ISSUE THREAD

**Issue by aliasgerkw** [checkly/public-roadmap#82]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
We are using tags to distinguish checks as per teams. If there is a way to get tags in slack notification particular team can act on it instead of pinging multiple peoples to take the ownership.

**Describe the solution you'd like**
Just add one more field tags in slack message.

**Describe alternatives you've considered**
I was thinking to rename checks and appending tags name in title itself

**Additional context**
<img width="906" alt="Screenshot 2020-10-20 at 2 58 55 PM" src="https://user-images.githubusercontent.com/51911147/96567826-e0e6d600-12e4-11eb-8949-b9329490da6e.png">

**Comment by tnolet** [comment]
@aliasgerkw thanks for reporting. This seems like a quick & easy win for everyone. I'm marking this as "accepted".

**Comment by umutuzgur** [comment]
Hey @aliasgerkw, we have just released this and tags are now added to the Slack alerts. Thanks a lot for pointing out!

**Comment by aliasgerkw** [comment]
Thanks @umutuzgur 
Will check and let you know. Thanks team!

**Comment by aliasgerkw** [comment]
@umutuzgur Seems tag is added only for failure intimation. Better if we have the same for kind of alerts
cc: @tnolet 
![Uploading Screenshot 2020-10-26 at 8.41.09 PM.png…]()

**Comment by tnolet** [comment]
@aliasgerkw hmmm 🧐 I will check this tomorrow. Thanks for reporting!

**Comment by tnolet** [comment]
@aliasgerkw this fix is shipping today! We quite literally forgot this.
