### ISSUE TITLE
Timestamp in alert in page header for "started failing" shows most recent failure

### ISSUE THREAD

**Issue by wvanderdeijl** [checkly/public-roadmap#83]
Hi,

This is the header I see at the top of a page for a specific check:
![image](https://user-images.githubusercontent.com/7952432/96708805-0a156e00-139a-11eb-8847-e2b17fd11543.png)

But if I look at the failed attempts, you can see that it has been failing since 11:43, not 11:58
![image](https://user-images.githubusercontent.com/7952432/96708875-231e1f00-139a-11eb-956f-2d22efbe0fee.png)

**Comment by wvanderdeijl** [comment]
This was after a new (recurring) maintenance period had started (at 12:00). Not sure if that is relevant to this bug

**Comment by tnolet** [comment]
@wvanderdeijl that's not how it should be! Let me confirm and then we pick it up as a bug.

**Comment by tnolet** [comment]
@wvanderdeijl yes, this is a UI bug. We found the issue and will ship a fix.

**Comment by umutuzgur** [comment]
Hi @wvanderdeijl, this issue is fixed and deployed. Thanks a lot for reporting this bug!
