### ISSUE TITLE
Delay CI/CD checks after enqueueing

### ISSUE THREAD

**Issue by geoffharcourt** [checkly/public-roadmap#86]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
Hi! We use preboot on Heroku, which means that our new application's code may not be fully available for a few minutes after we deploy. Heroku issues a deployment status event to Github as soon as the deployment starts, but we've found in our monitoring that it can be 3-4 minutes before every request is being served by the new code. This means that Checkly checks (and our other monitoring) might run prematurely against the old code and give a false positive success. 

Our review applications on Heroku build seed data after their first deployment, so we have a similar situation where we want to delay the checks until the basic seeds are in place to allow realistic checks against endpoints, etc.

**Describe the solution you'd like**
We'd like to be able to specify a delay interval (something like 3 minutes in our case) between when Github gets the deployment status event and Checkly kicks off the CI/CD check with the Github integration.

**Describe alternatives you've considered**

- adding a sleep statement in our check setup, but that seems rude!
- moving to a trigger-based check and leveraging our own delay, but that seems prone to flakiness

**Additional context**

**Comment by tnolet** [comment]
@geoffharcourt thanks for reporting this. Seems like a clear and useful feature.

**Comment by tnolet** [comment]
@geoffharcourt I'm closing this issue as we now give you full control over when checks are created/updated and triggered in CI/CD using our CLI. Have a look at our updated docs https://www.checklyhq.com/docs/cli
