### ISSUE TITLE
Surface HTTP status code in Webhook Alerts

### ISSUE THREAD

**Issue by aodhgan** [checkly/public-roadmap#88]
Is your feature request related to a problem? Please describe.
Currently we have an API check on an endpoint that is sometimes faulty, but this does not accurately reflect the service we are interested in monitoring behind it. It would be nice to know if it is just this gateway endpoint failing in the alert.

Describe the solution you'd like
Be able to include the check's HTTP status code in the body of the webhook message with the handlebar syntax. 

Describe alternatives you've considered
Having a parallel check assert just on the HTTP status.

Additional context

**Comment by tnolet** [comment]
@aodhgan this is a great contribution and we will ship this in the coming days

**Comment by tnolet** [comment]
@aodhgan we just add two new variables to the webhooks: `API_CHECK_RESPONSE_STATUS_CODE ` and `API_CHECK_RESPONSE_STATUS_TEXT`. You can use them in your webhooks as follows:

```json
{
   "code": "{{API_CHECK_RESPONSE_STATUS_CODE}}"
}

Also see:

https://www.checklyhq.com/docs/alerting/webhooks/#using-variables
