### ISSUE TITLE
API Access to Job Log

### ISSUE THREAD

**Issue by ragog** [checkly/public-roadmap#90]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
Users often print extra information (e.g. debugging info, performance results, ...) in the check job log. Right now the job log is only accessible through the Checkly UI.

**Describe the solution you'd like**
Making the job log retrievable through the API (https://www.checklyhq.com/docs/api#retrieve-a-check-result? it could maybe be part of browserCheckResult?) would open up opportunities for users to consume this additional information automatically.

**Describe alternatives you've considered**
So far, I have found no alternative.

**Comment by mauryaratan** [comment]
+1

**Comment by tnolet** [comment]
@ragog @mauryaratan @karolinaBM @RemyOuviere we just shipped an update to our public API that allow you to get all the logs and more. The full lowdown is described in this issue comment https://github.com/checkly/public-roadmap/issues/162#issuecomment-1032434211
