### ISSUE TITLE
Checkly should identify itself via User-Agent Header

### ISSUE THREAD

**Issue by shakalandy** [checkly/public-roadmap#91]
**Is your feature request related to a problem? Please describe.**
The default User-Agent Checkly is currently using in API tests is empty (User-Agent=""). 
Although this is configurable I would propose to have a default user-agent set, for API and Browser Checks.

**Describe the solution you'd like**
Set default user-agent for Checkly (including website link) to make transparent that the regular checkly bot "hello" is intended and necessary.

**Describe alternatives you've considered**
none.

**Additional context**
Please check here vor an overview of Google Bot identifiers: https://developers.google.com/search/docs/advanced/crawling/overview-google-crawlers?hl=de

StatusPizza identifies as: 
```
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.4 (KHTML, like Gecko) Chrome/98 Safari/537.4 (StatusCake)
```

MyDear as following: 
``` 
"Mozilla/5.0 (compatible; OhDear/1.1; +https://ohdear.app/checker; Run 3450034512)"
```

**Comment by umutuzgur** [comment]
Hi @shakalandy, we just made a release where checkly is now setting the user-agent for browser and api checks. You can still override them both if you would like. Thanks for creating the feature request!
