### ISSUE TITLE
Add pulumi provider

### ISSUE THREAD

**Issue by healyworld-sre** [checkly/public-roadmap#97]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
We're planning to move away from CDK (typescript) & Terraform to use Pulumi (Go), it would be nice to be able to define the whole infrastructure in a single IaC tool, so we wouldn't rely on Terraform for checkly anymore.

**Describe the solution you'd like**
Please create a pulumi provider for checkly.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by tnolet** [comment]
@healyworld-sre thanks for reporting. Building a Pulumi provider next to our Terraform provider is not on our roadmap right now. It would be quite a big time investment, specifically the ongoing maintenance as we develop the core product further and further. I would love to see more requests / upvotes for this.

**Comment by ianaya89** [comment]
[Here](https://github.com/checkly/pulumi-chekly) is the repo of the Pulumi provider, is in a really early stage but I was able to start creating Checkly resources from JavaScript and TypeScript.

The provider is using the TF bridge strategy, which means that every single thing we support on Terraform will be supported on Pulumi as well.

**Comment by tnolet** [comment]
This feature is now live and ready for everyone to use. We will follow up with a proper marketing release also. Check the installation and configuration docs on the Pulumi registry https://www.pulumi.com/registry/packages/checkly/installation-configuration/
