### ISSUE TITLE
Broken link for "the app settings on Github"

### ISSUE THREAD

**Issue by wzulfikar** [checkly/public-roadmap#98]
**Is your feature request related to a problem? Please describe.**
When I click the Github settings link in Checkly integration page, it will redirect to Github 404 page. The link address (eg. `https://github.com/settings/installations/<app_id>`) is correct if I'm doing the integration for my personal Github account. But if the integration is for Github organization account, it should be `https://github.com/organizations/<organization_name>/settings/installations/<app_id>`.

**Describe the solution you'd like**
It would be good if Checkly can identify whether a Github integration belongs to personal account or organization account. 
- If it's personal account, link to `https://github.com/settings/installations/<app_id>`
- If it's organization account, link to `https://github.com/organizations/<organization_name>/settings/installations/<app_id>`

**Describe alternatives you've considered**
I've had to manually visit the "Installed Github Apps" page of my Github organization (eg. `https://github.com/organizations/<organization_name>/settings/installations`) when I need to configure Checkly integration.

**Additional context**

1. Checkly integration page
![image](https://user-images.githubusercontent.com/7823011/107142908-eee06580-696c-11eb-880f-973d4368a380.png)
2. Github 404 page (after clicking the link in Checkly)
![image](https://user-images.githubusercontent.com/7823011/107143051-c60ca000-696d-11eb-822a-744d8c053a86.png)

**Comment by tnolet** [comment]
hey @wzulfikar this is indeed a know bug on our side. We have it on our internal bug tracker. Sadly, the GitHub API is a bit non intuitive here. I hope the workaround works for you until we fix this.

**Comment by wzulfikar** [comment]
Alright noted!

**Comment by chocolateofpain** [comment]
Hi @wzulfikar, the issue should be completely fixed now!

**Comment by tnolet** [comment]
@chocolateofpain I closed the issue.
